#!/usr/bin/env node

/*
 * Copyright Elasticsearch B.V. and/or licensed to Elasticsearch B.V. under one
 * or more contributor license agreements. Licensed under the Elastic License
 * 2.0 and the Server Side Public License, v 1; you may not use this file except
 * in compliance with, at your election, the Elastic License 2.0 or the Server
 * Side Public License, v 1.
 */

/**
 * Generates typed illustration modules from raw SVGs.
 *
 * Authoring workflow for designers:
 *   1. Export the illustration from Figma for both color modes.
 *   2. Drop the two files into `src/svgs` as:
 *        <name>.light.svg
 *        <name>.dark.svg
 *   3. Run `yarn generate` (build/test scripts run it automatically).
 *
 * Everything under `src/generated` is produced by this script (do not edit).
 */

const fs = require('fs');
const path = require('path');
const { optimize } = require('svgo');

const svgsDir = path.resolve(__dirname, '../src/svgs');
const outputDir = path.resolve(__dirname, '../src/generated');

const SVG_FILE = /^(.+)\.(light|dark)\.svg$/;

const svgoConfig = {
  multipass: true,
  plugins: [
    { name: 'preset-default', params: { overrides: { removeViewBox: false } } },
    'removeDimensions',
  ],
};

/** `data-viz`/`data_viz` -> `dataViz` for a valid JS identifier. */
const toCamelCase = (name) =>
  name.replace(/[-_](.)/g, (_, char) => char.toUpperCase());

/**
 * A generated export must be a valid JS identifier, otherwise the generated
 * modules won't compile. Catches leading digits (`3d-map` -> `3dMap`), spaces
 * and any other stray characters the file name may contain.
 */
const isValidIdentifier = (identifier) => /^[A-Za-z_$][\w$]*$/.test(identifier);

/** `data-viz` -> `Data viz` for a human-readable title. */
const toTitle = (name) => {
  const words = name.replace(/[-_]+/g, ' ').trim();
  return words.charAt(0).toUpperCase() + words.slice(1);
};

const optimizeSvg = (filePath) => {
  const raw = fs.readFileSync(filePath, 'utf8');
  const { data } = optimize(raw, { ...svgoConfig, path: filePath });
  return data;
};

const collectIllustrations = () => {
  if (!fs.existsSync(svgsDir)) {
    throw new Error(`Missing SVG source directory: ${svgsDir}`);
  }

  const byName = new Map();
  const errors = [];

  for (const fileName of fs.readdirSync(svgsDir).sort()) {
    if (!fileName.endsWith('.svg')) continue;

    const match = fileName.match(SVG_FILE);
    if (!match) {
      errors.push(
        `"${fileName}" is not a recognized name. Use <name>.light.svg / <name>.dark.svg`
      );
      continue;
    }

    const [, name, mode] = match;
    const record = byName.get(name) ?? {};
    record[mode] = path.join(svgsDir, fileName);
    byName.set(name, record);
  }

  const illustrations = [];

  for (const [name, modes] of byName) {
    if (!modes.light) errors.push(`"${name}" is missing ${name}.light.svg`);
    if (!modes.dark) errors.push(`"${name}" is missing ${name}.dark.svg`);
    if (!modes.light || !modes.dark) continue;

    const exportName = toCamelCase(name);
    if (!isValidIdentifier(exportName)) {
      errors.push(
        `"${name}" produces an invalid JS export name "${exportName}". Use a name that starts with a letter and contains only letters, numbers, "-" or "_".`
      );
      continue;
    }

    illustrations.push({
      id: name,
      exportName,
      title: toTitle(name),
      light: optimizeSvg(modes.light),
      dark: optimizeSvg(modes.dark),
    });
  }

  if (errors.length) {
    throw new Error(`Illustration SVGs are invalid:\n  - ${errors.join('\n  - ')}`);
  }

  return illustrations.sort((a, b) => a.id.localeCompare(b.id));
};

const AUTOGEN_HEADER =
  '// AUTO-GENERATED by scripts/generate.js — do not edit.\n' +
  '// Add SVGs to src/svgs (see the script header for layouts) and run `yarn generate`.\n';

const renderModule = ({ exportName, id, title, light, dark }) =>
  `${AUTOGEN_HEADER}
import type { EuiIllustrationSource } from '../types';

export const ${exportName}: EuiIllustrationSource = {
  id: ${JSON.stringify(id)},
  title: ${JSON.stringify(title)},
  light: ${JSON.stringify(light)},
  dark: ${JSON.stringify(dark)},
};
`;

const renderIndex = (illustrations) => {
  const imports = illustrations
    .map(({ exportName, id }) => `import { ${exportName} } from './${id}';`)
    .join('\n');
  const reExports = illustrations
    .map(({ exportName, id }) => `export { ${exportName} } from './${id}';`)
    .join('\n');
  const record = illustrations
    .map(({ exportName }) => `  ${exportName},`)
    .join('\n');

  return `${AUTOGEN_HEADER}
import type { EuiIllustrationSource } from '../types';
${imports}

${reExports}

export const illustrations: Readonly<Record<string, EuiIllustrationSource>> = {
${record}
};
`;
};

const main = () => {
  const illustrations = collectIllustrations();

  fs.rmSync(outputDir, { recursive: true, force: true });
  fs.mkdirSync(outputDir, { recursive: true });

  for (const illustration of illustrations) {
    fs.writeFileSync(
      path.join(outputDir, `${illustration.id}.ts`),
      renderModule(illustration)
    );
  }

  fs.writeFileSync(path.join(outputDir, 'index.ts'), renderIndex(illustrations));

  const names = illustrations.map(({ id }) => id).join(', ') || '(none)';
  console.log(
    `Generated ${illustrations.length} illustration(s) into src/generated: ${names}`
  );
};

main();
