
export const EXAMPLE_CAL_RANGE = [
  { numberedDay: 26 },
  { numberedDay: 27 },
  { numberedDay: 28 },
  { numberedDay: 29 },
  { numberedDay: 30 },
  { numberedDay: 1, isInTheCurrentMonth: true },
  { numberedDay: 2, isInTheCurrentMonth: true },
  { numberedDay: 3, isInTheCurrentMonth: true },
  { numberedDay: 4, isInTheCurrentMonth: true },
  { numberedDay: 5, isInTheCurrentMonth: true },
  { numberedDay: 6, isInTheCurrentMonth: true },
  { numberedDay: 7, isInTheCurrentMonth: true, isToday: true },
  { numberedDay: 8, isInTheCurrentMonth: true, isSelected: true, isStartDate: true },
  { numberedDay: 9, isInTheCurrentMonth: true, isSelected: true },
  { numberedDay: 10, isInTheCurrentMonth: true, isSelected: true },
  { numberedDay: 11, isInTheCurrentMonth: true, isSelected: true },
  { numberedDay: 12, isInTheCurrentMonth: true, isSelected: true },
  { numberedDay: 13, isInTheCurrentMonth: true, isSelected: true },
  { numberedDay: 14, isInTheCurrentMonth: true, isSelected: true, isEndDate: true },
  { numberedDay: 15, isInTheCurrentMonth: true },
  { numberedDay: 16, isInTheCurrentMonth: true },
  { numberedDay: 17, isInTheCurrentMonth: true },
  { numberedDay: 18, isInTheCurrentMonth: true },
  { numberedDay: 19, isInTheCurrentMonth: true },
  { numberedDay: 20, isInTheCurrentMonth: true },
  { numberedDay: 21, isInTheCurrentMonth: true },
  { numberedDay: 22, isInTheCurrentMonth: true },
  { numberedDay: 23, isInTheCurrentMonth: true },
  { numberedDay: 24, isInTheCurrentMonth: true },
  { numberedDay: 25, isInTheCurrentMonth: true },
  { numberedDay: 26, isInTheCurrentMonth: true },
  { numberedDay: 27, isInTheCurrentMonth: true },
  { numberedDay: 28, isInTheCurrentMonth: true },
  { numberedDay: 29, isInTheCurrentMonth: true },
  { numberedDay: 30, isInTheCurrentMonth: true },
  { numberedDay: 31, isInTheCurrentMonth: true },
  { numberedDay: 1 },
  { numberedDay: 2 },
  { numberedDay: 3 },
  { numberedDay: 4 },
  { numberedDay: 5 },
  { numberedDay: 6 },
];

export const EXAMPLE_CAL_SINGLE_DATE = [
  { numberedDay: 26 },
  { numberedDay: 27 },
  { numberedDay: 28 },
  { numberedDay: 29 },
  { numberedDay: 30 },
  { numberedDay: 1, isInTheCurrentMonth: true },
  { numberedDay: 2, isInTheCurrentMonth: true },
  { numberedDay: 3, isInTheCurrentMonth: true },
  { numberedDay: 4, isInTheCurrentMonth: true },
  { numberedDay: 5, isInTheCurrentMonth: true },
  { numberedDay: 6, isInTheCurrentMonth: true },
  { numberedDay: 7, isInTheCurrentMonth: true, isToday: true },
  { numberedDay: 8, isInTheCurrentMonth: true },
  { numberedDay: 9, isInTheCurrentMonth: true },
  { numberedDay: 10, isInTheCurrentMonth: true },
  { numberedDay: 11, isInTheCurrentMonth: true },
  { numberedDay: 12, isInTheCurrentMonth: true },
  { numberedDay: 13, isInTheCurrentMonth: true },
  { numberedDay: 14, isInTheCurrentMonth: true, isStartDate: true },
  { numberedDay: 15, isInTheCurrentMonth: true },
  { numberedDay: 16, isInTheCurrentMonth: true },
  { numberedDay: 17, isInTheCurrentMonth: true },
  { numberedDay: 18, isInTheCurrentMonth: true },
  { numberedDay: 19, isInTheCurrentMonth: true },
  { numberedDay: 20, isInTheCurrentMonth: true },
  { numberedDay: 21, isInTheCurrentMonth: true },
  { numberedDay: 22, isInTheCurrentMonth: true },
  { numberedDay: 23, isInTheCurrentMonth: true },
  { numberedDay: 24, isInTheCurrentMonth: true },
  { numberedDay: 25, isInTheCurrentMonth: true },
  { numberedDay: 26, isInTheCurrentMonth: true },
  { numberedDay: 27, isInTheCurrentMonth: true },
  { numberedDay: 28, isInTheCurrentMonth: true },
  { numberedDay: 29, isInTheCurrentMonth: true },
  { numberedDay: 30, isInTheCurrentMonth: true },
  { numberedDay: 31, isInTheCurrentMonth: true },
  { numberedDay: 1 },
  { numberedDay: 2 },
  { numberedDay: 3 },
  { numberedDay: 4 },
  { numberedDay: 5 },
  { numberedDay: 6 },
];
