rules:
  # Order how you please
  property-sort-order: 0
  mixins-before-declarations:
    - 2
    -
      exclude: ['euiBreakpoint', 'euiCanAnimate']
  # Use none instead of 0 for no border
  border-zero:
    - 2
    - convention: 'none'
  force-element-nesting: 0
  force-pseudo-nesting: 0
  # We minify css, so this doesn't apply
  no-css-comments: 0
  # We use _ (underscores) for import path that don't directly compile
  clean-import-paths: 0
  # Allows input[type=search]
  force-attribute-nesting: 0
  no-qualifying-elements:
    - 2
    -
      # Allows input[type=search]
      allow-element-with-attribute: 1
  # Files can end without a newline
  final-newline: 0
  # Warns are nice for deprecations and development
  no-warn: 0
  # Transition all is useful in certain situations and there's no recent info to suggest slowdown
  no-transition-all: 0
