nmHoistingLimits: none

nodeLinker: node-modules

npmRegistryServer: "https://registry.npmjs.org/"

plugins:
  - checksum: bf17e6e7142b3162823b1e75ae1581114be48682c0f04d79bf8ddafeb32562e41b6f314d4caa9c5731d59a3ca18a6c9490a0241ccc03aa59e680bc2bbc320ff3
    path: .yarn/plugins/@yarnpkg/plugin-eui-validate-env.cjs
    spec: packages/yarn-plugin-validate-env/bundles/@yarnpkg/plugin-eui-validate-env.js

yarnPath: .yarn/releases/yarn-4.6.0.cjs
