################################################################################
###################### catalog-info for EUI ######################
# Declare a Backstage Component that represents your application.
---
# yaml-language-server: $schema=https://json.schemastore.org/catalog-info.json
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: eui
  description: Elastic design system library
  links: [
    {
      url: "https://eui.elastic.co/#/",
      title: "EUI documentation",
    }
  ]
  tags: ["eui", "kibana", "typescript"]

spec:
  type: library
  owner: group:eui-team
  system: ci-systems
  lifecycle: production

###############################################################################
############################# Buildkite pipelines ##############################
# Declare your Buildkite pipeline.
# This declaration creates the Backstage entity and the pipeline in Buildkite.
---
# yaml-language-server: $schema=https://gist.githubusercontent.com/elasticmachine/988b80dae436cafea07d9a4a460a011d/raw/e57ee3bed7a6f73077a3f55a38e76e40ec87a7cf/rre.schema.json
apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: buildkite-pipeline-eui
  description: EUI example pipeline that echoes a greeting
  links: [
    {
      title: "EUI - example pipeline",
      url: "https://buildkite.com/elastic/eui",
    }
  ]
      
spec:
  type: buildkite-pipeline
  owner: group:eui-team
  system: buildkite
  implementation:
    apiVersion: buildkite.elastic.dev/v1
    kind: Pipeline
    metadata:
      name: eui
    spec:
      repository: elastic/eui
      pipeline_file: ".buildkite/pipeline.yml"
      teams:
        eui-team:
         access_level: MANAGE_BUILD_AND_READ
        everyone:
          access_level: READ_ONLY

############################ Pull request test #############################
# Run all unit and functional tests on PR
---
# yaml-language-server: $schema=https://gist.githubusercontent.com/elasticmachine/988b80dae436cafea07d9a4a460a011d/raw/e57ee3bed7a6f73077a3f55a38e76e40ec87a7cf/rre.schema.json
apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: buildkite-pipeline-eui-pull-request-test
  description: EUI pipeline to run unit and functional tests on pull request
  links: [
    {
      title: "EUI - pull-request-test",
      url: "https://buildkite.com/elastic/eui-pull-request-test",
    }
  ]
      
spec:
  type: buildkite-pipeline
  owner: group:eui-team
  system: buildkite
  implementation:
    apiVersion: buildkite.elastic.dev/v1
    kind: Pipeline
    metadata:
      name: eui-pull-request-test
    spec:
      repository: elastic/eui
      pipeline_file: ".buildkite/pipelines/pipeline_pull_request_test.yml"
      # Pull request test - only run when code is pushed to feature/buildkite-migration branch. For now.
      provider_settings:
        build_branches: true
        build_tags: false
        build_pull_requests: false
        filter_enabled: true
        filter_condition: build.branch == "feature/buildkite-migration"
      teams:
        eui-team:
         access_level: MANAGE_BUILD_AND_READ
        everyone:
          access_level: READ_ONLY

############################ Pull request deploy docs #############################
# Deploy docs to cloud on PR
---
# yaml-language-server: $schema=https://gist.githubusercontent.com/elasticmachine/988b80dae436cafea07d9a4a460a011d/raw/e57ee3bed7a6f73077a3f55a38e76e40ec87a7cf/rre.schema.json
apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: buildkite-pipeline-eui-pull-request-deploy-docs
  description: EUI pipeline to deploy docs to cloud on pull request
  links: [
    {
      title: "EUI - pull-request-deploy-docs",
      url: "https://buildkite.com/elastic/eui-pull-request-deploy-docs",
    }
  ]
      
spec:
  type: buildkite-pipeline
  owner: group:eui-team
  system: buildkite
  implementation:
    apiVersion: buildkite.elastic.dev/v1
    kind: Pipeline
    metadata:
      name: eui-pull-request-deploy-docs
    spec:
      repository: elastic/eui
      pipeline_file: ".buildkite/pipelines/pipeline_pull_request_deploy_docs.yml"
      # Pull request deploy docs - only run when code is pushed to feature/buildkite-migration branch. For now.
      provider_settings:
        build_branches: true
        build_tags: false
        build_pull_requests: false
        filter_enabled: true
        filter_condition: build.branch == "feature/buildkite-migration"
      teams:
        eui-team:
         access_level: MANAGE_BUILD_AND_READ
        everyone:
          access_level: READ_ONLY
