################################################################################
###################### catalog-info for EUI ######################
# Declare a Backstage Component that represents your application.
---
# yaml-language-server: $schema=https://json.schemastore.org/catalog-info.json
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: eui
  description: Elastic design system library
  links: [
    {
      url: "https://eui.elastic.co/#/",
      title: "EUI documentation",
    }
  ]
  tags: ["eui", "kibana", "typescript"]

spec:
  type: library
  owner: group:eui-team
  system: ci-systems
  lifecycle: production

###############################################################################
############################# Buildkite pipelines ##############################
# Declare your Buildkite pipeline.
# This declaration creates the Backstage entity and the pipeline in Buildkite.
---
# yaml-language-server: $schema=https://gist.githubusercontent.com/elasticmachine/988b80dae436cafea07d9a4a460a011d/raw/e57ee3bed7a6f73077a3f55a38e76e40ec87a7cf/rre.schema.json
apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: buildkite-pipeline-eui
  description: EUI example pipeline that echoes a greeting
  links: [
    {
      title: "EUI - example pipeline",
      url: "https://buildkite.com/elastic/eui",
    }
  ]
      
spec:
  type: buildkite-pipeline
  owner: group:eui-team
  system: buildkite
  implementation:
    apiVersion: buildkite.elastic.dev/v1
    kind: Pipeline
    metadata:
      name: eui
    spec:
      repository: elastic/eui
      pipeline_file: ".buildkite/pipeline.yml"
      default_branch: main
      # Setting all triggers to false to prevent the default job from running.
      # Keeping the job available if needed for smoke testing during the migration.
      provider_settings:
        build_branches: false
        build_tags: false
        build_pull_requests: false
      teams:
        eui-team:
         access_level: MANAGE_BUILD_AND_READ
        everyone:
          access_level: READ_ONLY

############################ Pull request test #############################
# Run all unit and functional tests on PR
---
# yaml-language-server: $schema=https://gist.githubusercontent.com/elasticmachine/988b80dae436cafea07d9a4a460a011d/raw/e57ee3bed7a6f73077a3f55a38e76e40ec87a7cf/rre.schema.json
apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: buildkite-pipeline-eui-pull-request-test
  description: EUI pipeline to run unit and functional tests on pull request
  links: [
    {
      title: "EUI - pull-request-test",
      url: "https://buildkite.com/elastic/eui-pull-request-test",
    }
  ]
      
spec:
  type: buildkite-pipeline
  owner: group:eui-team
  system: buildkite
  implementation:
    apiVersion: buildkite.elastic.dev/v1
    kind: Pipeline
    metadata:
      name: eui-pull-request-test
    spec:
      repository: elastic/eui
      pipeline_file: ".buildkite/pipelines/pipeline_pull_request_test.yml"
      default_branch: main
      cancel_intermediate_builds: true
      # Job runs as a step in pull request combined job
      provider_settings:
        build_branches: false
        build_tags: false
        build_pull_requests: false
      teams:
        eui-team:
         access_level: MANAGE_BUILD_AND_READ
        everyone:
          access_level: BUILD_AND_READ

############################ Pull request deploy docs #############################
# Deploy docs to cloud on PR
---
# yaml-language-server: $schema=https://gist.githubusercontent.com/elasticmachine/988b80dae436cafea07d9a4a460a011d/raw/e57ee3bed7a6f73077a3f55a38e76e40ec87a7cf/rre.schema.json
apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: buildkite-pipeline-eui-pull-request-deploy-docs
  description: EUI pipeline to deploy docs to cloud on pull request
  links: [
    {
      title: "EUI - pull-request-deploy-docs",
      url: "https://buildkite.com/elastic/eui-pull-request-deploy-docs",
    }
  ]
      
spec:
  type: buildkite-pipeline
  owner: group:eui-team
  system: buildkite
  implementation:
    apiVersion: buildkite.elastic.dev/v1
    kind: Pipeline
    metadata:
      name: eui-pull-request-deploy-docs
    spec:
      repository: elastic/eui
      pipeline_file: ".buildkite/pipelines/pipeline_pull_request_deploy_docs.yml"
      default_branch: main
      cancel_intermediate_builds: true
      # Job runs as a step in pull request combined job
      provider_settings:
        build_branches: false
        build_tags: false
        build_pull_requests: false
      teams:
        eui-team:
         access_level: MANAGE_BUILD_AND_READ
        everyone:
          access_level: BUILD_AND_READ


############################ Pull request combined job #############################
# Orchestrate tests and deploying docs to cloud on branch PR
---
# yaml-language-server: $schema=https://gist.githubusercontent.com/elasticmachine/988b80dae436cafea07d9a4a460a011d/raw/e57ee3bed7a6f73077a3f55a38e76e40ec87a7cf/rre.schema.json
apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: buildkite-pipeline-eui-pull-request-test-and-deploy
  description: EUI pipeline to run tests and deploy docs to cloud on branch pull request
  links: [
    {
      title: "EUI - pull-request-test-and-deploy",
      url: "https://buildkite.com/elastic/eui-pull-request-test-and-deploy",
    }
  ]
      
spec:
  type: buildkite-pipeline
  owner: group:eui-team
  system: buildkite
  implementation:
    apiVersion: buildkite.elastic.dev/v1
    kind: Pipeline
    metadata:
      name: eui-pull-request-test-and-deploy
    spec:
      repository: elastic/eui
      pipeline_file: ".buildkite/pipelines/pipeline_pull_request_test_and_deploy.yml"
      default_branch: main
      env:
        ELASTIC_PR_COMMENTS_ENABLED: 'true'
      cancel_intermediate_builds: true
      provider_settings:
        build_branches: false
        build_tags: false
        build_pull_requests: true
      teams:
        eui-team:
         access_level: MANAGE_BUILD_AND_READ
        everyone:
          access_level: BUILD_AND_READ


############################ Release deploy docs #############################
# Publish docs to EUI subdomain when we tag a new release
---
# yaml-language-server: $schema=https://gist.githubusercontent.com/elasticmachine/988b80dae436cafea07d9a4a460a011d/raw/e57ee3bed7a6f73077a3f55a38e76e40ec87a7cf/rre.schema.json
apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: buildkite-pipeline-eui-release-deploy-docs
  description: EUI pipeline to deploy docs to the EUI subdomain when we tag a new release
  links: [
    {
      title: "EUI - release-deploy-docs",
      url: "https://buildkite.com/elastic/eui-release-deploy-docs",
    }
  ]

spec:
  type: buildkite-pipeline
  owner: group:eui-team
  system: buildkite
  implementation:
    apiVersion: buildkite.elastic.dev/v1
    kind: Pipeline
    metadata:
      name: eui-release-deploy-docs
    spec:
      repository: elastic/eui
      pipeline_file: ".buildkite/pipelines/pipeline_release_deploy_docs.yml"
      default_branch: main
      provider_settings:
        build_branches: false
        build_tags: true # Will trigger job when GitHub tags are created
        build_pull_requests: false
      teams:
        eui-team:
         access_level: MANAGE_BUILD_AND_READ
        everyone:
          access_level: READ_ONLY
