import { IconSearchSynonyms } from './icon_filter';

export const iconSynonyms: IconSearchSynonyms = {
  accessibility: [
    'a11y',
    'inclusive',
    'disability',
    'wcag',
    'assistive',
    'screen reader',
    'universal design',
  ],
  addToDashboard: [
    'dashboard',
    'add',
    'pin',
    'widget',
    'panel',
    'insert',
    'save view',
  ],
  aggregate: ['combine', 'sum', 'group', 'collection', 'merge', 'total', 'rollup'],
  alignBottom: ['align', 'bottom', 'vertical', 'position', 'layout', 'dock'],
  alignBottomLeft: ['align', 'bottom', 'left', 'corner', 'position', 'layout'],
  alignBottomRight: ['align', 'bottom', 'right', 'corner', 'position', 'layout'],
  alignCenterHorizontal: [
    'align',
    'center',
    'horizontal',
    'middle',
    'position',
    'layout',
  ],
  alignCenterVertical: [
    'align',
    'center',
    'vertical',
    'middle',
    'position',
    'layout',
  ],
  alignLeft: ['align', 'left', 'horizontal', 'position', 'layout', 'flush'],
  alignRight: ['align', 'right', 'horizontal', 'position', 'layout', 'flush'],
  alignTop: ['align', 'top', 'vertical', 'position', 'layout', 'dock'],
  alignTopLeft: ['align', 'top', 'left', 'corner', 'position', 'layout'],
  alignTopRight: ['align', 'top', 'right', 'corner', 'position', 'layout'],
  archive: [
    'storage',
    'box',
    'store',
    'backup',
    'file away',
    'saved',
    'repository',
  ],
  asterisk: ['star', 'wildcard', 'required', 'multiply', 'reference', 'footnote'],
  at: ['email', 'mention', 'address', 'symbol', 'contact', 'handle'],
  axisX: ['x axis', 'horizontal axis', 'chart', 'graph', 'dimension', 'abscissa'],
  axisYLeft: ['y axis', 'left', 'vertical axis', 'chart', 'graph', 'ordinate'],
  axisYRight: ['y axis', 'right', 'vertical axis', 'chart', 'graph', 'ordinate'],
  backgroundTask: ['background', 'async', 'job', 'task', 'process', 'worker', 'queue'],
  bell: [
    'notification',
    'alert',
    'alarm',
    'notify',
    'ring',
    'reminder',
    'announcements',
  ],
  bellSlash: [
    'mute',
    'notification off',
    'silence',
    'bell disabled',
    'alerts off',
    'quiet',
  ],
  beta: ['greek', 'test', 'experimental', 'preview', 'version', 'letter'],
  bolt: ['lightning', 'fast', 'power', 'electric', 'speed', 'energy'],
  branch: ['git', 'version control', 'fork', 'tree', 'split', 'divergence'],
  briefcase: ['work', 'business', 'job', 'portfolio', 'office', 'career'],
  broom: ['clean', 'sweep', 'clear', 'tidy', 'wipe', 'brush off'],
  brush: ['paint', 'draw', 'art', 'design', 'stroke', 'brush tool'],
  bug: ['insect', 'defect', 'issue', 'error', 'debug', 'glitch'],
  bulb: ['light', 'idea', 'lamp', 'insight', 'bright', 'hint'],
  bullseye: [
    'findings',
    'target',
    'aim',
    'goal',
    'focus',
    'dartboard',
    'precision',
    'center',
  ],
  calendar: ['date', 'schedule', 'event', 'day', 'month', 'time'],
  chartAnomaly: ['anomaly', 'chart', 'outlier', 'detection', 'spike', 'unusual'],
  chartArea: ['area chart', 'graph', 'visualization', 'filled', 'trend', 'plot'],
  chartAreaStack: [
    'stacked area',
    'chart',
    'graph',
    'layers',
    'visualization',
    'plot',
  ],
  chartBarHorizontal: [
    'bar chart',
    'horizontal',
    'graph',
    'bars',
    'visualization',
    'plot',
  ],
  chartBarHorizontalStack: [
    'stacked bar',
    'horizontal',
    'chart',
    'graph',
    'grouped',
    'plot',
  ],
  chartBarVertical: [
    'bar chart',
    'vertical',
    'graph',
    'columns',
    'visualization',
    'plot',
  ],
  chartBarVerticalStack: [
    'stacked bar',
    'vertical',
    'chart',
    'graph',
    'grouped',
    'plot',
  ],
  chartChangePoint: [
    'change point',
    'chart',
    'breakpoint',
    'shift',
    'detection',
    'regime',
  ],
  chartGauge: ['gauge', 'meter', 'dial', 'chart', 'metric', 'speedometer'],
  chartHeatmap: ['heatmap', 'matrix', 'density', 'chart', 'grid', 'correlation'],
  chartLine: [
    'line chart',
    'graph',
    'trend',
    'visualization',
    'plot',
    'time series',
  ],
  chartMetric: ['metric', 'chart', 'kpi', 'measurement', 'stat', 'indicator'],
  chartPie: ['pie chart', 'donut', 'proportion', 'circle', 'segments', 'share'],
  chartTagCloud: ['tag cloud', 'word cloud', 'text', 'chart', 'keywords', 'frequency'],
  chartThreshold: ['threshold', 'limit', 'chart', 'boundary', 'alert line', 'cutoff'],
  chartWaterfall: [
    'waterfall chart',
    'cascade',
    'steps',
    'bridge',
    'cumulative',
    'breakdown',
  ],
  check: ['tick', 'confirm', 'done', 'yes', 'approve', 'mark'],
  checkCircle: ['check', 'circle', 'success', 'confirm', 'complete', 'ok'],
  checkCircleFill: ['check', 'filled', 'success', 'confirm', 'complete', 'ok'],
  chevronDoubleLeft: ['chevron', 'double', 'left', 'rewind', 'back', 'previous'],
  chevronDoubleRight: ['chevron', 'double', 'right', 'forward', 'skip', 'next'],
  chevronLimitLeft: ['chevron', 'limit', 'first', 'start', 'beginning', 'jump', 'skip'],
  chevronLimitRight: ['chevron', 'limit', 'last', 'end', 'final', 'jump', 'skip'],
  chevronSingleDown: ['chevron', 'down', 'dropdown', 'expand', 'arrow', 'caret'],
  chevronSingleLeft: ['chevron', 'left', 'back', 'previous', 'arrow', 'caret'],
  chevronSingleRight: ['chevron', 'right', 'next', 'forward', 'arrow', 'caret'],
  chevronSingleUp: ['chevron', 'up', 'collapse', 'arrow', 'caret'],
  clickLeft: ['click', 'left', 'mouse', 'pointer', 'button', 'tap'],
  clickRight: ['click', 'right', 'mouse', 'context', 'button', 'tap'],
  clock: ['clock'],
  clockControl: ['clock', 'control', 'time', 'schedule', 'timer', 'settings'],
  clockCounter: ['clock', 'counter', 'countdown', 'timer', 'time', 'elapsed'],
  cloud: ['cloud', 'online', 'hosting', 'saas', 'remote'],
  cluster: ['cluster', 'nodes', 'group', 'collection', 'distributed'],
  code: ['code', 'developer', 'programming', 'script', 'source'],
  commandLine: ['terminal', 'cli', 'console', 'shell', 'command', 'prompt'],
  comment: ['comment', 'chat', 'message', 'feedback', 'discussion'],
  compare: ['compare', 'diff', 'versus', 'side by side'],
  contrast: ['contrast', 'accessibility', 'visibility', 'a11y'],
  contrastFill: ['contrast', 'filled', 'accessibility', 'visibility', 'a11y', 'display'],
  controls: ['controls', 'sliders', 'settings', 'adjust', 'panel'],
  copy: ['duplicate', 'clone', 'clipboard', 'replicate', 'paste'],
  cross: ['cross', 'close', 'cancel', 'delete'],
  crossCircle: ['cross circle', 'cross', 'close', 'cancel', 'delete', 'circle'],
  crosshair: ['crosshair'],
  crossProjectSearch: ['search', 'cross project', 'global', 'find', 'lookup', 'explore'],
  dashedCircle: ['dashed', 'circle', 'pending', 'incomplete', 'outline', 'status'],
  database: ['database', 'data', 'storage', 'sql', 'records'],
  display: ['display'],
  distributeHorizontal: ['distribute horizontal', 'distribute', 'horizontal'],
  distributeVertical: ['distribute vertical', 'distribute', 'vertical'],
  document: ['document', 'file', 'page', 'paper', 'doc'],
  documentation: ['documentation', 'docs', 'help', 'guide', 'manual'],
  documents: ['documents', 'files', 'pages', 'papers', 'library'],
  dot: ['dot', 'point', 'bullet', 'period', 'circle'],
  download: ['save', 'export', 'retrieve', 'get file', 'arrow down', 'pull'],
  drag: ['drag', 'move', 'grab', 'reorder', 'handle'],
  dragHorizontal: ['drag horizontal', 'drag', 'move', 'grab', 'reorder', 'handle', 'horizontal'],
  dragVertical: ['drag vertical', 'drag', 'move', 'grab', 'reorder', 'handle', 'vertical'],
  ellipsis: ['ellipsis', 'more', 'menu', 'overflow', 'dots'],
  empty: ['empty', 'blank', 'none', 'placeholder', 'void'],
  endpoint: ['endpoint', 'api', 'url', 'connection', 'target'],
  eraser: ['eraser', 'clear', 'remove', 'delete', 'rubber'],
  error: ['error', 'failure', 'problem', 'invalid', 'cross'],
  errorFill: ['error fill', 'error', 'failure', 'problem', 'invalid', 'cross', 'fill', 'filled'],
  external: ['external', 'open new', 'link out', 'outside'],
  eye: ['eye', 'view', 'visible', 'show', 'preview', 'watch'],
  eyeSlash: ['eye slash', 'eye', 'view', 'visible', 'show', 'preview', 'watch', 'slash'],
  faceHappy: ['smile', 'happy', 'emoji', 'positive', 'grin', 'satisfied', 'mood'],
  faceNeutral: ['face neutral', 'face', 'neutral'],
  faceSad: ['face sad', 'face', 'sad'],
  filter: ['funnel', 'refine', 'narrow', 'sort', 'subset', 'sieve', 'criteria'],
  filterExclude: ['filter', 'exclude', 'remove', 'minus', 'refine', 'narrow'],
  filterIgnore: ['filter', 'ignore', 'skip', 'exclude', 'omit', 'hide'],
  filterInclude: ['filter', 'include', 'add', 'refine', 'narrow', 'select'],
  flag: ['flag', 'mark', 'report', 'bookmark', 'priority'],
  flask: ['flask', 'experiment', 'lab', 'science', 'test'],
  folderClose: ['folder', 'closed', 'collapse', 'directory', 'archive'],
  folderOpen: ['folder', 'open', 'expand', 'directory', 'browse'],
  fullScreen: ['fullscreen'],
  fullScreenExit: ['fullscreen', 'exit', 'minimize', 'window', 'restore', 'shrink'],
  gear: [
    'settings',
    'configure',
    'configuration',
    'preferences',
    'options',
    'cog',
    'setup',
    'admin',
    'wrench',
  ],
  globe: ['globe', 'world', 'web', 'internet', 'international'],
  gradient: ['gradient', 'blend', 'fade', 'color transition'],
  grid: ['grid', 'table', 'layout', 'matrix', 'cells'],
  heart: ['heart', 'favorite', 'like', 'love', 'bookmark'],
  home: ['home', 'house', 'main', 'start', 'dashboard'],
  hourglass: ['hourglass', 'waiting', 'loading', 'time', 'pending'],
  if: ['if', 'condition', 'logic', 'branch', 'rule'],
  image: ['image', 'picture', 'photo', 'media', 'graphic'],
  indexClose: ['index', 'close', 'elasticsearch', 'dataset', 'remove'],
  indexEdit: ['index', 'edit', 'elasticsearch', 'dataset', 'modify', 'settings'],
  indexOpen: ['index', 'open', 'elasticsearch', 'dataset', 'browse'],
  indexRuntime: ['index', 'runtime', 'elasticsearch', 'live', 'execution'],
  indexSettings: ['index', 'settings', 'elasticsearch', 'configure', 'options'],
  infinity: ['infinity', 'unlimited', 'forever', 'loop', 'endless'],
  info: ['info', 'information', 'help', 'about', 'details'],
  inputOutput: ['input', 'output', 'io', 'data flow', 'pipeline', 'stream'],
  inspect: ['inspect', 'investigate', 'examine', 'analyze', 'look'],
  key: ['key', 'password', 'credential', 'access', 'security'],
  keyboard: ['keyboard', 'typing', 'input', 'shortcut', 'keys'],
  kubernetesPod: ['kubernetes', 'pod', 'k8s', 'container', 'cluster', 'orchestration'],
  layers: ['layers'],
  lineBreak: ['line break', 'newline', 'paragraph', 'text', 'wrap', 'return'],
  lineBreakSlash: ['line break', 'slash', 'text', 'separator', 'paragraph'],
  lineDash: ['line dash', 'line', 'dash'],
  lineDot: ['line dot', 'line', 'dot', 'point', 'bullet', 'period', 'circle'],
  lineSolid: ['line solid', 'line', 'solid'],
  link: ['link', 'url', 'chain', 'connect', 'hyperlink'],
  linkSlash: ['unlink', 'broken link', 'remove link', 'disconnect', 'url'],
  listBullet: ['list bullet', 'list', 'bullet', 'items', 'rows'],
  listCheck: ['list check', 'list', 'bullet', 'items', 'rows', 'check', 'tick', 'confirm'],
  listNumber: ['list number', 'list', 'bullet', 'items', 'rows', 'number', 'digit', 'numeric'],
  lock: ['lock', 'secure', 'private', 'protected', 'password'],
  lockOpen: ['lock open', 'lock', 'secure', 'private', 'protected', 'password', 'open'],
  logOut: ['log out', 'log', 'out'],
  magnify: ['search', 'find', 'zoom', 'lookup', 'query', 'discover', 'glass'],
  magnifyExclamation: ['search', 'alert', 'warning', 'find', 'magnify', 'important'],
  magnifyMinus: ['zoom out', 'search', 'minus', 'shrink', 'magnify'],
  magnifyPlus: ['zoom in', 'search', 'plus', 'enlarge', 'magnify'],
  mail: ['mail', 'email', 'envelope', 'message', 'inbox'],
  map: ['map', 'location', 'geo', 'geography', 'region'],
  mapping: ['mapping'],
  maximize: ['maximize'],
  megaphone: ['megaphone', 'announce', 'broadcast', 'marketing', 'loud'],
  menu: ['menu', 'hamburger', 'navigation', 'options', 'bars'],
  menuLeft: ['menu left', 'menu', 'hamburger', 'navigation', 'options', 'bars', 'left'],
  menuRight: ['menu right', 'menu', 'hamburger', 'navigation', 'options', 'bars', 'right'],
  merge: ['merge', 'combine', 'join', 'unite', 'git'],
  minimize: ['minimize'],
  minus: ['minus', 'remove', 'subtract', 'decrement'],
  minusCircle: ['minus circle', 'minus', 'remove', 'subtract', 'decrement', 'circle'],
  minusSquare: ['minus', 'square', 'remove', 'collapse', 'decrement'],
  money: ['money', 'payment', 'billing', 'cost', 'finance'],
  moon: ['moon', 'dark', 'night', 'theme'],
  move: ['move', 'relocate', 'drag', 'position', 'transfer'],
  nested: ['nested', 'hierarchy', 'tree', 'child', 'indent'],
  number: ['number', 'digit', 'numeric', 'count', 'hash'],
  package: ['package', 'box', 'bundle', 'npm', 'module'],
  pagesSelect: ['pages', 'select', 'pagination', 'choose', 'document'],
  paintBucket: ['paint', 'fill', 'bucket', 'color', 'flood fill'],
  palette: ['palette', 'colors', 'theme', 'design', 'swatch'],
  paperClip: ['attachment', 'clip', 'file', 'attach', 'paperclip'],
  partial: ['partial', 'incomplete', 'fragment', 'section'],
  pattern: ['pattern', 'texture', 'repeat', 'design', 'fill'],
  pause: ['pause', 'hold', 'stop temporary', 'wait'],
  pencil: ['pencil', 'edit', 'write', 'modify', 'pen'],
  percent: ['percent', 'percentage', 'ratio', 'rate'],
  pin: ['pin', 'anchor', 'stick', 'fixed', 'bookmark'],
  pinFill: ['pin', 'filled', 'stick', 'anchor', 'fixed', 'bookmark'],
  pivot: ['pivot', 'table', 'transform', 'rotate', 'analytics'],
  play: ['play', 'start', 'run', 'media', 'video'],
  plus: ['plus', 'add', 'new', 'create', 'increment'],
  plusCircle: ['plus circle', 'plus', 'add', 'new', 'create', 'increment', 'circle'],
  plusSquare: ['plus', 'square', 'add', 'expand', 'increment'],
  popper: ['popper', 'tooltip', 'overlay', 'popup', 'floating'],
  presentation: ['presentation', 'slides', 'deck', 'display', 'show'],
  processor: ['processor', 'compute', 'cpu', 'transform', 'ingest'],
  productAgent: ['agent', 'product', 'elastic agent', 'fleet', 'monitoring'],
  productCloudInfra: ['cloud', 'infrastructure', 'product', 'hosting', 'platform'],
  productDashboard: ['dashboard', 'product', 'kibana', 'analytics', 'panel'],
  productDiscover: ['discover', 'product', 'explore', 'data', 'search', 'kibana'],
  productML: ['machine learning', 'ml', 'product', 'model', 'ai'],
  productStreamsClassic: ['streams', 'classic', 'product', 'data', 'pipeline'],
  productStreamsWired: ['streams', 'wired', 'product', 'data', 'pipeline', 'connected'],
  query: ['query', 'search', 'sql', 'lucene', 'filter'],
  queryField: ['query', 'field', 'filter', 'column', 'attribute', 'selector'],
  queryOperand: ['query', 'operand', 'operator', 'logic', 'condition', 'rule'],
  querySelector: ['query', 'selector', 'pick', 'choose', 'field', 'filter'],
  queryValue: ['query', 'value', 'literal', 'data', 'input', 'filter'],
  question: ['question', 'help', 'unknown', 'faq', 'ask'],
  queue: ['queue', 'line', 'buffer', 'waiting', 'jobs'],
  quote: ['quote', 'citation', 'blockquote', 'text'],
  radar: ['radar', 'scan', 'detect', 'monitor', 'signal'],
  readOnly: ['read only', 'locked', 'view', 'permission', 'restrict'],
  redo: ['redo', 'repeat', 'forward', 'again'],
  refresh: ['refresh', 'reload', 'sync', 'update', 'rotate'],
  refreshTime: ['refresh', 'time', 'reload', 'schedule', 'sync', 'clock'],
  reporter: ['reporter', 'report', 'export', 'document', 'output'],
  return: ['return', 'enter', 'keyboard', 'submit', 'back', 'revert'],
  rocket: ['rocket', 'launch', 'deploy', 'fast', 'startup'],
  save: ['save', 'store', 'disk', 'persist', 'keep'],
  scissors: ['scissors'],
  section: ['section', 'region', 'block', 'area', 'group'],
  send: ['send', 'submit', 'dispatch', 'arrow', 'share'],
  server: ['server', 'host', 'machine', 'infrastructure', 'backend'],
  shard: ['shard', 'partition', 'segment', 'elastic', 'index'],
  share: ['share', 'send', 'distribute', 'social', 'export'],
  significantEvents: ['events', 'significant', 'anomaly', 'alert', 'notable', 'timeline'],
  snowflake: ['snowflake', 'unique', 'id', 'data warehouse'],
  sortable: ['sortable', 'sort', 'order'],
  sortAscending: ['sort', 'ascending', 'up', 'order', 'rank', 'increase'],
  sortDescending: ['sort', 'descending', 'down', 'order', 'rank', 'decrease'],
  sortDown: ['sort down', 'sort', 'order', 'rank', 'arrange', 'down'],
  sortLeft: ['sort left', 'sort', 'order', 'rank', 'arrange', 'left'],
  sortRight: ['sort right', 'sort', 'order', 'rank', 'arrange', 'right'],
  sortUp: ['sort up', 'sort', 'order', 'rank', 'arrange', 'up'],
  sparkles: ['sparkles', 'ai', 'magic', 'new', 'enhance', 'auto'],
  star: ['star', 'favorite', 'rating', 'bookmark'],
  starFill: ['star fill', 'star', 'favorite', 'rating', 'bookmark', 'fill', 'filled', 'solid'],
  stop: ['stop', 'halt', 'end', 'terminate', 'square'],
  storage: ['storage', 'disk', 'drive', 'save', 'data store'],
  sun: ['sun', 'light', 'day', 'theme', 'bright'],
  symlink: ['symlink', 'shortcut', 'alias', 'link', 'reference'],
  table: ['table'],
  tableDensityHigh: ['table', 'density', 'compact', 'tight', 'rows', 'spacing'],
  tableDensityLow: ['table', 'density', 'spacious', 'loose', 'rows', 'spacing'],
  tableInfo: ['table', 'info', 'metadata', 'details', 'schema', 'columns'],
  tableTime: ['table', 'time', 'temporal', 'date', 'timeline', 'history'],
  tag: ['tag', 'label', 'category', 'keyword', 'badge'],
  text: ['text'],
  textAlignCenter: ['text', 'align', 'center', 'middle', 'typography'],
  textAlignLeft: ['text', 'align', 'left', 'typography', 'paragraph'],
  textAlignRight: ['text', 'align', 'right', 'typography', 'paragraph'],
  textBold: ['text bold', 'text', 'bold', 'typography', 'formatting'],
  textHeading: ['text', 'heading', 'title', 'h1', 'typography', 'header'],
  textItalic: ['text italic', 'text', 'italic', 'typography', 'formatting'],
  textStrike: ['text', 'strikethrough', 'strike', 'delete', 'typography'],
  textUnderline: ['text underline', 'text', 'underline', 'typography', 'formatting'],
  thermometer: ['thermometer', 'temperature', 'heat', 'metric', 'gauge'],
  thumbDown: ['thumbs down', 'dislike', 'negative', 'vote', 'feedback', 'bad'],
  thumbUp: ['thumbs up', 'like', 'positive', 'vote', 'feedback', 'good'],
  timeline: ['timeline', 'history', 'events', 'chronological', 'sequence'],
  timelineWithArrow: ['timeline', 'arrow', 'history', 'sequence', 'flow', 'events'],
  transitionBottomIn: ['transition', 'bottom', 'in', 'animate', 'enter', 'motion'],
  transitionBottomOut: ['transition', 'bottom', 'out', 'animate', 'exit', 'motion'],
  transitionLeftIn: ['transition', 'left', 'in', 'animate', 'enter', 'motion'],
  transitionLeftOut: ['transition', 'left', 'out', 'animate', 'exit', 'motion'],
  transitionTopIn: ['transition', 'top', 'in', 'animate', 'enter', 'motion'],
  transitionTopOut: ['transition', 'top', 'out', 'animate', 'exit', 'motion'],
  trash: ['trash', 'delete', 'remove', 'bin', 'garbage', 'discard'],
  unarchive: ['unarchive', 'restore', 'extract', 'retrieve', 'unpack'],
  undo: ['undo', 'revert', 'back', 'previous action'],
  upload: ['upload', 'import', 'send', 'cloud', 'arrow up'],
  user: ['user', 'person', 'account', 'profile', 'avatar'],
  users: ['users', 'people', 'team', 'group', 'accounts'],
  vectorSquare: ['vector', 'square', 'shape', 'geometry', 'box', 'region'],
  vectorTriangle: ['vector', 'triangle', 'shape', 'geometry', 'delta'],
  videoPlayer: ['video', 'player', 'play', 'media', 'film', 'watch'],
  warning: ['warning', 'alert', 'caution', 'danger', 'issue'],
  warningFill: ['warning fill', 'warning', 'alert', 'caution', 'danger', 'issue', 'fill', 'filled'],
  waypoint: ['waypoint', 'marker', 'step', 'node', 'path'],
  wifi: ['wifi', 'wireless', 'network', 'internet', 'connection'],
  wifiSlash: ['wifi', 'off', 'disconnected', 'network', 'wireless', 'no signal'],
  workflow: ['workflow', 'automation', 'pipeline', 'process', 'flow'],
  wrench: ['wrench', 'tool', 'fix', 'settings', 'repair'],
};
