name: Check changelog
description: Ensures each modified package has a changelog entry in changelogs/upcoming
inputs:
  pr-number:
    required: true
    description: PR number used as the changelog filename
  package-path:
    required: false
    description: Specific package path to check (e.g., packages/eui). If not provided, checks all packages.
runs:
  using: 'composite'
  steps:
    - name: Check for changelog entry
      shell: bash
      run: .github/actions/check-changelog/entrypoint.sh
      env:
        PR_NUMBER: ${{ inputs.pr-number }}
        PACKAGE_PATH: ${{ inputs.package-path }}

