name: Hidden test
description: Internal use only
labels: ["internal"]
hidden: true
body:
  - type: textarea
    id: everything
    attributes:
      label: Hidden Template
      value: |
        This is a hidden issue template.
