import React, { Fragment } from 'react';

import { ExternalBadge } from './shared';

import {
  EuiCode,
  EuiCodeBlock,
  EuiSpacer,
  EuiFlexGroup,
  EuiFlexItem,
  EuiCard,
  EuiIcon,
  EuiText,
} from '../../../../src/components';
import { TextureMultiSeriesChart } from './texture';

const warningCard = [
  {
    title: 'Warning',
    iconType: 'alert',
    iconColor: 'warning',
    description: (
      <>
        Currently, data tables are only available for{' '}
        <strong>partition charts</strong>{' '}
      </>
    ),
  },
];

export const ElasticChartsAccessiblityExample = {
  title: 'Accessibility Features in Elastic Charts',
  intro: (
    <Fragment>
      <ExternalBadge />
      <EuiSpacer size="l" />
      <EuiText>
        Elastic charts is becoming more and more accessible for users of
        assistive technologies.
      </EuiText>
      <EuiSpacer />
      <EuiText>
        <strong>Available a11y configurations</strong>
      </EuiText>
      <EuiText>
        <ul>
          <li>ariaDescription/ariaDescribedBy</li>
          <li>ariaLabel/ariaLabelledBy</li>
          <li>ariaLabelHeadingLevel</li>
          <li>ariaUseDefaultSummary/ariaTableCaption</li>
          <li>texture fill for xy charts</li>
        </ul>
      </EuiText>
    </Fragment>
  ),
  sections: [
    {
      title: 'ariaDescription and ariaDescribedBy',
      text: (
        <>
          The <EuiCode>{'ariaDescription'}</EuiCode> and{' '}
          <EuiCode>{'ariaDescribedBy'}</EuiCode> can be set the through the{' '}
          <EuiCode>{'<Settings />'}</EuiCode> component. You can pass in a
          description of the chart through the{' '}
          <EuiCode>{'ariaDescription'}</EuiCode> prop. The text will be a
          visually hidden <EuiCode>{'p'}</EuiCode> element by default. You can
          set the aria-describedby of the chart <EuiCode>{'<canvas>'}</EuiCode>{' '}
          element and then use the id elsewhere in your app.
          <EuiSpacer />
          If you specify both a <EuiCode>{'ariaDescription'}</EuiCode> and{' '}
          <EuiCode>{'ariaDescribedBy'}</EuiCode>, the
          <EuiCode>{'ariaDescribedBy'}</EuiCode> will override the
          <EuiCode>{'ariaDescription'}</EuiCode> prop.
          <EuiSpacer />
          <EuiCodeBlock language="javascript" isCopyable fontSize="s">
            {`<Settings 
ariaDescription="This chart has three different types of series. There is a bar, line and area series." 
ariaUseDefaultSummary={false}
/>`}
          </EuiCodeBlock>
        </>
      ),
    },
    {
      title: 'ariaLabel and ariaLabelledBy',
      text: (
        <>
          Within the <EuiCode>{'<Settings />'}</EuiCode> component, you can add
          your own aria-label on the figure surrounding the chart element. Use
          the <EuiCode>{'ariaLabel'}</EuiCode> prop on the{' '}
          <EuiCode>{'<Settings />'}</EuiCode> component.
          <EuiSpacer />
          The aria-labeledby can be set with the{' '}
          <EuiCode>{'ariaLabelledBy'}</EuiCode> prop to tie the charts to other
          accessible elements within your app.
        </>
      ),
    },
    {
      title: 'ariaLabelHeadingLevel',
      text: (
        <>
          You can also change the heading level (instead of{' '}
          <EuiCode>{'p'}</EuiCode> as the default) by passing the
          ariaLabelHeadingLevel to the
          <EuiCode>{'<Settings />'}</EuiCode> component. Valid options are{' '}
          <EuiCode>{`h1,
          h2, h3, h4, h5, h6,`}</EuiCode>{' '}
          or
          <EuiCode>{'p'}</EuiCode>.
        </>
      ),
    },
    {
      title: 'ariaUseDefaultSummary and ariaTableCaption',
      text: (
        <>
          The default description generated by elastic charts can be disabled by
          setting <EuiCode>{'ariaUseDefaultSummary={false}'}</EuiCode> in the{' '}
          <EuiCode>{'<Settings />'}</EuiCode> component.
          <EuiSpacer />
          <EuiCode>{'ariaTableCaption'}</EuiCode> is available to set a caption
          to the data table for users of assistive technologies.
          <EuiSpacer />
          <EuiFlexGroup responsive={false} wrap>
            {warningCard.map((card) => (
              <EuiFlexItem key={card.title} style={{ minWidth: 170 }}>
                <EuiCard
                  layout="horizontal"
                  title={
                    <EuiFlexGroup
                      gutterSize="s"
                      responsive={false}
                      alignItems="center">
                      <EuiFlexItem grow={false}>
                        <EuiIcon type={card.iconType} color={card.iconColor} />
                      </EuiFlexItem>
                      <EuiFlexItem>{card.title}</EuiFlexItem>
                    </EuiFlexGroup>
                  }
                  titleElement="h2"
                  description={card.description}
                />
              </EuiFlexItem>
            ))}
          </EuiFlexGroup>
        </>
      ),
    },
    {
      title: 'Texture',
      text: (
        <>
          You can set the fill for area charts with texture fills with the{' '}
          <EuiCode>{'TextureStyles interface'}</EuiCode>
          <EuiSpacer />
          <EuiCodeBlock language="javascript">
            {`interface TexturedStylesBase {
  /** polygon fill color for texture */
  fill?: Color | ColorVariant;
  /** polygon stroke color for texture */
  stroke?: Color | ColorVariant;
  /** polygon stroke width for texture  */
  strokeWidth?: number;
  /** polygon opacity for texture  */
  opacity?: number;
  /** polygon opacity for texture  */
  dash?: number[];
  /** polygon opacity for texture  */
  size?: number;
  /**
   * The angle of rotation for entire texture
   * in degrees
   */
  rotation?: number;
  /**
   * The angle of rotation for polygons
   * in degrees
   */
  shapeRotation?: number;
  /** texture spacing between polygons */
  spacing?: Partial<Point> | number;
  /** overall origin offset of pattern */
  offset?: Partial<Point> & {
    /** apply offset along global coordinate axes */
    global?: boolean;
  };
}

interface TexturedShapeStyles extends TexturedStylesBase {
  /** typed of texture designs currently supported */
  shape: TextureShape;
}

interface TexturedPathStyles extends TexturedStylesBase {
  /** path for polygon texture */
  path: string | Path2D;
}

/**
 * @public
 *
 * Texture style config for area spec
 */
export type TexturedStyles = TexturedPathStyles | TexturedShapeStyles;`}
          </EuiCodeBlock>
        </>
      ),
      demo: <TextureMultiSeriesChart />,
      snippet: `
    <Chart size={{ height: 200 }}>
      <BarSeries
        key={1}
        id={'series-1'}
        barSeriesStyle={{
          rect: {
            opacity: 0.2,
            texture: {
              opacity: 1,
              offset: { x: undefined, y: undefined },
              rotation: undefined,
              shape: 'square',
              shapeRotation: undefined,
              size: 9,
              spacing: { x: undefined, y: undefined },
            },
          },
        }}
        stackAccessors={['yes']}
        data={SAMPLE_SMALL_DATA}
        curve={CurveType.CURVE_MONOTONE_X}
      />
      <AreaSeries
        key={2}
        id={'series-2'}
        areaSeriesStyle={{
          area: {
            opacity: 0.05,
            shape: 'circle',
            texture: {
              opacity: 1,
              shape: 'circle',
              rotation: undefined,
              shapeRotation: undefined,
              size: 5,
              spacing: {
                x: 0,
                y: 0,
              },
              offset: {
                x: 0,
                y: 1,
              },
            },
          },
        }}
        data={SAMPLE_SMALL_DATA_2}
      />
    </Chart>`,
    },
  ],
};
