#!/usr/bin/env bash

set -e

NODE_IMG="docker.elastic.co/eui/ci:5.3"

# Compile using node image
echo "Building docs using ${NODE_IMG} Docker image"
docker pull $NODE_IMG
docker run \
    --rm -i \
    --env HOME=/tmp \
    --"user=$(id -u)":"$(id -g)" \
    --volume "$PWD":/app \
    --workdir /app \
    $NODE_IMG \
    bash -c 'yarn && npm run build && npm run build-docs'
