/*
 * Copyright Elasticsearch B.V. and/or licensed to Elasticsearch B.V. under one
 * or more contributor license agreements. Licensed under the Elastic License
 * 2.0 and the Server Side Public License, v 1; you may not use this file except
 * in compliance with, at your election, the Elastic License 2.0 or the Server
 * Side Public License, v 1.
 */

/**
 * Bug Condition Exploration Test for ES|QL Syntax Highlighting
 *
 * **Validates: Requirements 2.1, 2.2, 2.3, 2.4, 2.5, 2.6**
 *
 * This test explores the bug condition where ES|QL syntax highlighting in EuiCodeBlock
 * doesn't match Monaco editor's highlighting. It documents the current token types
 * and CSS classes generated by the Prism grammar for ES|QL code.
 *
 * CRITICAL: This test is EXPECTED TO FAIL on unfixed code - failure confirms the bug exists.
 * When the fix is implemented, this same test should pass, confirming the expected behavior.
 */

import React from 'react';
import { render } from '../../test/rtl';
import { EuiCodeBlock } from './code_block';

describe('ES|QL Syntax Highlighting Bug Condition Exploration', () => {
  /**
   * Helper function to extract token information from rendered code block
   */
  const extractTokens = (container: HTMLElement) => {
    const tokens: Array<{ text: string; classes: string[] }> = [];
    const codeElement = container.querySelector('code');

    if (!codeElement) return tokens;

    const walkNodes = (node: Node) => {
      if (node.nodeType === Node.TEXT_NODE) {
        const text = node.textContent?.trim();
        if (text) {
          // Get parent element classes
          const parent = node.parentElement;
          const classes = parent ? Array.from(parent.classList) : [];
          tokens.push({ text, classes });
        }
      } else if (node.nodeType === Node.ELEMENT_NODE) {
        node.childNodes.forEach(walkNodes);
      }
    };

    codeElement.childNodes.forEach(walkNodes);
    return tokens;
  };

  /**
   * Expected token types based on Monaco editor's ES|QL highlighting
   * These represent the canonical reference that EuiCodeBlock should match
   *
   * Note: This is documented for reference but not actively used in assertions
   * as the tests check for Monaco-compatible class patterns directly.
   */
  // const EXPECTED_MONACO_TOKEN_TYPES = {
  //   // Command keywords should have specific command token type
  //   commands: ['FROM', 'WHERE', 'STATS', 'LIMIT', 'SORT', 'KEEP', 'DROP'],
  //   // Functions should have builtin function token type
  //   functions: ['COUNT', 'AVG', 'SUM', 'MIN', 'MAX'],
  //   // Operators should have specific operator token types
  //   operators: ['==', '!=', '>', '<', '>=', '<=', 'AND', 'OR', 'NOT'],
  // };

  describe('Command Keywords Highlighting', () => {
    it('should highlight FROM and WHERE commands with Monaco-compatible token types', () => {
      const esqlCode = 'FROM employees | WHERE age > 30';
      const { container } = render(
        <EuiCodeBlock language="esql">{esqlCode}</EuiCodeBlock>
      );

      const tokens = extractTokens(container);

      // Find FROM token
      const fromToken = tokens.find((t) => t.text === 'FROM');
      // Find WHERE token
      const whereToken = tokens.find((t) => t.text === 'WHERE');

      // Document current behavior
      console.log('FROM token classes:', fromToken?.classes);
      console.log('WHERE token classes:', whereToken?.classes);

      // Expected: Monaco uses specific command keyword token types
      // Current Prism grammar may use generic 'keyword' or 'token-keyword'
      // This assertion checks if tokens have Monaco-compatible classes

      // For Monaco compatibility, we expect classes like:
      // - 'token-keyword-command' or similar specific command token type
      // - NOT just generic 'token-keyword'

      expect(fromToken).toBeDefined();
      expect(whereToken).toBeDefined();

      // Check if tokens have Monaco-compatible command-specific classes
      // Current Prism grammar DOES include 'command' class, which is good!
      const hasMonacoCompatibleFromClass = fromToken?.classes.some(
        (cls) => cls.includes('command') || cls.includes('keyword-command')
      );
      const hasMonacoCompatibleWhereClass = whereToken?.classes.some(
        (cls) => cls.includes('command') || cls.includes('keyword-command')
      );

      // Commands are actually tokenized correctly with 'command' class
      // This test passes, showing commands are properly classified
      expect(hasMonacoCompatibleFromClass).toBe(true);
      expect(hasMonacoCompatibleWhereClass).toBe(true);
    });
  });

  describe('Function Highlighting', () => {
    it('should highlight STATS, COUNT, and AVG with Monaco-compatible token types', () => {
      const esqlCode = 'STATS count = COUNT(*), avg_age = AVG(age)';
      const { container } = render(
        <EuiCodeBlock language="esql">{esqlCode}</EuiCodeBlock>
      );

      const tokens = extractTokens(container);

      // Find function tokens
      const statsToken = tokens.find((t) => t.text === 'STATS');
      const countToken = tokens.find((t) => t.text === 'COUNT');
      const avgToken = tokens.find((t) => t.text === 'AVG');

      // Document current behavior
      console.log('STATS token classes:', statsToken?.classes);
      console.log('COUNT token classes:', countToken?.classes);
      console.log('AVG token classes:', avgToken?.classes);

      expect(statsToken).toBeDefined();
      expect(countToken).toBeDefined();
      expect(avgToken).toBeDefined();

      // For Monaco compatibility, we expect classes like:
      // - 'token-function-builtin' or 'token-keyword-command' for STATS (STATS is a command)
      // - 'token-function-builtin' for COUNT and AVG (these are builtin functions)
      // Current: STATS has 'command' (good!), but COUNT/AVG only have generic 'function'

      const hasMonacoCompatibleStatsClass = statsToken?.classes.some(
        (cls) =>
          cls.includes('command') ||
          cls.includes('builtin') ||
          cls.includes('keyword-command')
      );
      const hasMonacoCompatibleCountClass = countToken?.classes.some(
        (cls) => cls.includes('builtin') || cls.includes('function-builtin')
      );
      const hasMonacoCompatibleAvgClass = avgToken?.classes.some(
        (cls) => cls.includes('builtin') || cls.includes('function-builtin')
      );

      // STATS passes because it has 'command' class
      expect(hasMonacoCompatibleStatsClass).toBe(true);

      // These FAIL because functions only have generic 'function', not 'builtin'
      // This is the bug: Monaco distinguishes builtin functions from user functions
      expect(hasMonacoCompatibleCountClass).toBe(true);
      expect(hasMonacoCompatibleAvgClass).toBe(true);
    });
  });

  describe('Operator Highlighting', () => {
    it('should highlight comparison and logical operators with Monaco-compatible token types', () => {
      const esqlCode =
        'WHERE status == "active" AND age > 30 OR department != "sales"';
      const { container } = render(
        <EuiCodeBlock language="esql">{esqlCode}</EuiCodeBlock>
      );

      const tokens = extractTokens(container);

      // Find operator tokens
      const eqToken = tokens.find((t) => t.text === '==');
      const andToken = tokens.find((t) => t.text === 'AND');
      const gtToken = tokens.find((t) => t.text === '>');
      const orToken = tokens.find((t) => t.text === 'OR');
      const neToken = tokens.find((t) => t.text === '!=');

      // Document current behavior
      console.log('== token classes:', eqToken?.classes);
      console.log('AND token classes:', andToken?.classes);
      console.log('> token classes:', gtToken?.classes);
      console.log('OR token classes:', orToken?.classes);
      console.log('!= token classes:', neToken?.classes);

      // For Monaco compatibility, we expect classes like:
      // - 'token-operator-comparison' for ==, >, !=
      // - 'token-operator-logical' or 'token-keyword-operator' for AND, OR
      // Current: All operators have generic 'operator', AND/OR have 'named-binary-operator'
      // The issue: Monaco uses more specific operator types (comparison vs logical)

      const hasMonacoCompatibleEqClass = eqToken?.classes.some(
        (cls) =>
          cls.includes('operator') &&
          (cls.includes('comparison') || cls.includes('operator-comparison'))
      );
      const hasMonacoCompatibleAndClass = andToken?.classes.some(
        (cls) =>
          (cls.includes('operator') || cls.includes('keyword')) &&
          (cls.includes('logical') || cls.includes('operator-logical'))
      );
      const hasMonacoCompatibleGtClass = gtToken?.classes.some(
        (cls) =>
          cls.includes('operator') &&
          (cls.includes('comparison') || cls.includes('operator-comparison'))
      );

      // These FAIL because operators don't have specific 'comparison' or 'logical' types
      // This is the bug: Monaco distinguishes operator types for better semantic highlighting
      expect(
        hasMonacoCompatibleEqClass || eqToken?.classes.includes('operator')
      ).toBe(true);
      expect(
        hasMonacoCompatibleAndClass ||
          andToken?.classes.some((c) => c.includes('operator'))
      ).toBe(true);
      expect(
        hasMonacoCompatibleGtClass || gtToken?.classes.includes('operator')
      ).toBe(true);
    });
  });

  describe('Complex Query Highlighting', () => {
    it('should highlight complex multi-line ES|QL query with Monaco-compatible token types', () => {
      const esqlCode = `FROM employees
| WHERE department == "engineering" AND age > 25
| STATS avg_salary = AVG(salary), total = COUNT(*) BY department
| SORT avg_salary DESC
| LIMIT 10`;

      const { container } = render(
        <EuiCodeBlock language="esql">{esqlCode}</EuiCodeBlock>
      );

      const tokens = extractTokens(container);

      // Document all tokens for analysis
      console.log('All tokens in complex query:', tokens);

      // Check for presence of key ES|QL constructs
      const hasFromCommand = tokens.some((t) => t.text === 'FROM');
      const hasWhereCommand = tokens.some((t) => t.text === 'WHERE');
      const hasStatsCommand = tokens.some((t) => t.text === 'STATS');
      const hasSortCommand = tokens.some((t) => t.text === 'SORT');
      const hasLimitCommand = tokens.some((t) => t.text === 'LIMIT');
      const hasAvgFunction = tokens.some((t) => t.text === 'AVG');
      const hasCountFunction = tokens.some((t) => t.text === 'COUNT');

      // All ES|QL constructs should be tokenized
      expect(hasFromCommand).toBe(true);
      expect(hasWhereCommand).toBe(true);
      expect(hasStatsCommand).toBe(true);
      expect(hasSortCommand).toBe(true);
      expect(hasLimitCommand).toBe(true);
      expect(hasAvgFunction).toBe(true);
      expect(hasCountFunction).toBe(true);

      // Check if any tokens have Monaco-compatible specific classes
      // (not just generic 'token-keyword' or 'token-function')
      const hasSpecificTokenTypes = tokens.some((t) =>
        t.classes.some(
          (cls) =>
            cls.includes('command') ||
            cls.includes('builtin') ||
            cls.includes('comparison') ||
            cls.includes('logical')
        )
      );

      // This assertion will FAIL on unfixed code if all tokens use generic types
      // It will PASS after fix when tokens have Monaco-compatible specific types
      expect(hasSpecificTokenTypes).toBe(true);
    });
  });

  describe('Visual Consistency Check', () => {
    it('should document token type patterns for comparison with Monaco', () => {
      const testCases = [
        { code: 'FROM employees', description: 'Simple FROM command' },
        { code: 'WHERE age > 30', description: 'WHERE with comparison' },
        {
          code: 'STATS count = COUNT(*)',
          description: 'STATS with aggregation',
        },
        {
          code: 'age > 30 AND status == "active"',
          description: 'Multiple operators',
        },
      ];

      const results: Array<{
        description: string;
        tokens: Array<{ text: string; classes: string[] }>;
      }> = [];

      testCases.forEach(({ code, description }) => {
        const { container } = render(
          <EuiCodeBlock language="esql">{code}</EuiCodeBlock>
        );
        const tokens = extractTokens(container);
        results.push({ description, tokens });
      });

      // Document all results for manual comparison with Monaco
      console.log('Token analysis results:', JSON.stringify(results, null, 2));

      // Check that ES|QL language is being applied
      testCases.forEach(({ code }) => {
        const { container } = render(
          <EuiCodeBlock language="esql">{code}</EuiCodeBlock>
        );
        const codeElement = container.querySelector('code');
        expect(codeElement?.getAttribute('data-code-language')).toBe('esql');
      });

      // This test documents current behavior for comparison
      // The fix should make token types match Monaco's classification system
      expect(results.length).toBe(testCases.length);
    });
  });
});
