name: Detect package changes
description: 'Detects which public packages have changed based on git diff'
outputs:
  changed-packages:
    description: 'A JSON array of changed public package names'
    value: ${{ steps.changes.outputs.changed-packages }}
runs:
  using: 'composite'
  steps:
    - name: Detect package changes
      id: changes
      shell: bash
      run: ${{ github.action_path }}/entrypoint.sh
