#!/bin/bash

if [[ "$BUILDKITE_AGENT_NAME" =~ ^bk-agent ]]; then
  source .buildkite/scripts/lifecycle/post_command.sh
else
  echo "Pipeline triggered from outside expected EUI workflow. Skipping post_command."
fi
