#!/bin/bash

if [[ "$BUILDKITE_AGENT_NAME" =~ ^bk-agent ]]; then
  source .buildkite/scripts/lifecycle/pre_command.sh
else
  echo "Pipeline triggered from outside expected EUI workflow. Skipping pre_command."
fi
