/*
 * Copyright Elasticsearch B.V. and/or licensed to Elasticsearch B.V. under one
 * or more contributor license agreements. Licensed under the Elastic License
 * 2.0 and the Server Side Public License, v 1; you may not use this file except
 * in compliance with, at your election, the Elastic License 2.0 or the Server
 * Side Public License, v 1.
 */

/// <reference types="cypress" />
/// <reference types="cypress-real-events" />
/// <reference types="../../../cypress/support" />

import React from 'react';
import { EuiIcon } from './icon';

describe('EuiIcons', () => {
  describe('Automated accessibility check for glyph icons', () => {
    const GlyphIcons = [
      'accessibility',
      'aggregate',
      'analyzeEvent',
      'annotation',
      'anomalySwimLane',
      'apps',
      'asterisk',
      'bell',
      'bellSlash',
      'beta',
      'bolt',
      'boxesVertical',
      'branch',
      'broom',
      'brush',
      'bug',
      'bullseye',
      'calendar',
      'check',
      'clock',
      'cloudDrizzle',
      'cloudStormy',
      'cloudSunny',
      'cluster',
      'container',
      'continuityAbove',
      'continuityWithin',
      'copy',
      'cross',
      'cube',
      'database',
      'document',
      'documents',
      'documentsCheck',
      'documentation',
      'dot',
      'download',
      'empty',
      'eraser',
      'esqlVis',
      'eye',
      'faceHappy',
      'faceNeutral',
      'faceSad',
      'filter',
      'filterExclude',
      'filterIgnore',
      'filterInclude',
      'flag',
      'fold',
      'folderCheck',
      'folderClosed',
      'folderExclamation',
      'folderOpen',
      'frameNext',
      'framePrevious',
      'fullScreen',
      'fullScreenExit',
      'gear',
      'globe',
      'grid',
      'heart',
      'help',
      'home',
      'info',
      'image',
      'index',
      'indexClose',
      'indexEdit',
      'indexOpen',
      'indexRuntime',
      'indexSettings',
      'infinity',
      'inputOutput',
      'inspect',
      'ip',
      'keyboard',
      'kqlFunction',
      'kubernetesPod',
      'layers',
      'lineSolid',
      'link',
      'lock',
      'lockOpen',
      'logstashFilter',
      'logstashInput',
      'logstashOutput',
      'memory',
      'merge',
      'menu',
      'menuDown',
      'menuLeft',
      'menuRight',
      'menuUp',
      'minimize',
      'minus',
      'mobile',
      'moon',
      'namespace',
      'nested',
      'number',
      'package',
      'pagesSelect',
      'paperClip',
      'partial',
      'pause',
      'payment',
      'pencil',
      'percent',
      'pin',
      'play',
      'plus',
      'question',
      'quote',
      'refresh',
      'reporter',
      'save',
      'sessionViewer',
      'shard',
      'share',
      'significantEvents',
      'snowflake',
      'sortable',
      'sortAscending',
      'sortDescending',
      'sortDown',
      'sortLeft',
      'sortRight',
      'sortUp',
      'singleMetricViewer',
      'spaces',
      'sparkles',
      'starEmptySpace',
      'starFillSpace',
      'starMinusEmpty',
      'starMinusFill',
      'starPlusEmpty',
      'starPlusFill',
      'stats',
      'stop',
      'stopSlash',
      'storage',
      'string',
      'sun',
      'symlink',
      'tableCross',
      'tableGear',
      'tableOfContents',
      'tablePencil',
      'tablePlay',
      'tablePlus',
      'tag',
      'timeline',
      'timelinePointer',
      'timelineWithArrow',
      'trash',
      'unfold',
      'user',
      'users',
      'videoPlayer',
      'visGoal',
      'visTimelion',
      'visVisualBuilder',
      'warning',
      'wordWrap',
      'wordWrapDisabled',
      'wrench',
    ];

    const GlyphGrid = () => (
      <div>
        {GlyphIcons.map((glyph) => (
          <EuiIcon className="eui-alignMiddle" type={glyph} />
        ))}
      </div>
    );

    it('has zero violations on first render', () => {
      cy.mount(<GlyphGrid />);
      cy.get('svg[data-icon-type="wrench"]', { timeout: 5000 }).should('exist');
      cy.checkAxe();
    });
  });
});
