import React, { useState } from 'react';

import {
  EuiSkeletonRectangle,
  EuiFlexGroup,
  EuiFlexItem,
  EuiSwitch,
  EuiSpacer,
  EuiImage,
  EuiBadge,
  EuiIcon,
} from '../../../../src/components';

export default () => {
  const [isLoading, setIsLoading] = useState(true);

  return (
    <>
      <EuiFlexGroup alignItems="center" justifyContent="spaceBetween">
        <EuiSwitch
          label="Toggle loaded state"
          checked={isLoading}
          onChange={() => setIsLoading(!isLoading)}
        />
      </EuiFlexGroup>
      <EuiSpacer />
      <EuiFlexGroup>
        <EuiFlexItem grow={false}>
          {isLoading ? (
            <EuiSkeletonRectangle width="16px" height="16px" borderRadius="s" />
          ) : (
            <EuiIcon type="cheer" />
          )}
        </EuiFlexItem>

        <EuiFlexItem grow={false}>
          {isLoading ? (
            <EuiSkeletonRectangle
              width="54.16px"
              height="20px"
              borderRadius="m"
            />
          ) : (
            <EuiBadge color="success">Active</EuiBadge>
          )}
        </EuiFlexItem>

        <EuiFlexItem grow={false}>
          {isLoading ? (
            <EuiSkeletonRectangle
              width="130px"
              height="130px"
              borderRadius="none"
            />
          ) : (
            <EuiImage
              alt="Many small white-spotted pink jellyfish floating in a dark aquarium"
              src="data:image/jpeg;base64, /9j/4AAQSkZJRgABAQEASABIAAD/4gxYSUNDX1BST0ZJTEUAAQEAAAxITGlubwIQAABtbnRyUkdCIFhZWiAHzgACAAkABgAxAABhY3NwTVNGVAAAAABJRUMgc1JHQgAAAAAAAAAAAAAAAAAA9tYAAQAAAADTLUhQICAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABFjcHJ0AAABUAAAADNkZXNjAAABhAAAAGx3dHB0AAAB8AAAABRia3B0AAACBAAAABRyWFlaAAACGAAAABRnWFlaAAACLAAAABRiWFlaAAACQAAAABRkbW5kAAACVAAAAHBkbWRkAAACxAAAAIh2dWVkAAADTAAAAIZ2aWV3AAAD1AAAACRsdW1pAAAD+AAAABRtZWFzAAAEDAAAACR0ZWNoAAAEMAAAAAxyVFJDAAAEPAAACAxnVFJDAAAEPAAACAxiVFJDAAAEPAAACAx0ZXh0AAAAAENvcHlyaWdodCAoYykgMTk5OCBIZXdsZXR0LVBhY2thcmQgQ29tcGFueQAAZGVzYwAAAAAAAAASc1JHQiBJRUM2MTk2Ni0yLjEAAAAAAAAAAAAAABJzUkdCIElFQzYxOTY2LTIuMQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAWFlaIAAAAAAAAPNRAAEAAAABFsxYWVogAAAAAAAAAAAAAAAAAAAAAFhZWiAAAAAAAABvogAAOPUAAAOQWFlaIAAAAAAAAGKZAAC3hQAAGNpYWVogAAAAAAAAJKAAAA+EAAC2z2Rlc2MAAAAAAAAAFklFQyBodHRwOi8vd3d3LmllYy5jaAAAAAAAAAAAAAAAFklFQyBodHRwOi8vd3d3LmllYy5jaAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABkZXNjAAAAAAAAAC5JRUMgNjE5NjYtMi4xIERlZmF1bHQgUkdCIGNvbG91ciBzcGFjZSAtIHNSR0IAAAAAAAAAAAAAAC5JRUMgNjE5NjYtMi4xIERlZmF1bHQgUkdCIGNvbG91ciBzcGFjZSAtIHNSR0IAAAAAAAAAAAAAAAAAAAAAAAAAAAAAZGVzYwAAAAAAAAAsUmVmZXJlbmNlIFZpZXdpbmcgQ29uZGl0aW9uIGluIElFQzYxOTY2LTIuMQAAAAAAAAAAAAAALFJlZmVyZW5jZSBWaWV3aW5nIENvbmRpdGlvbiBpbiBJRUM2MTk2Ni0yLjEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAHZpZXcAAAAAABOk/gAUXy4AEM8UAAPtzAAEEwsAA1yeAAAAAVhZWiAAAAAAAEwJVgBQAAAAVx/nbWVhcwAAAAAAAAABAAAAAAAAAAAAAAAAAAAAAAAAAo8AAAACc2lnIAAAAABDUlQgY3VydgAAAAAAAAQAAAAABQAKAA8AFAAZAB4AIwAoAC0AMgA3ADsAQABFAEoATwBUAFkAXgBjAGgAbQByAHcAfACBAIYAiwCQAJUAmgCfAKQAqQCuALIAtwC8AMEAxgDLANAA1QDbAOAA5QDrAPAA9gD7AQEBBwENARMBGQEfASUBKwEyATgBPgFFAUwBUgFZAWABZwFuAXUBfAGDAYsBkgGaAaEBqQGxAbkBwQHJAdEB2QHhAekB8gH6AgMCDAIUAh0CJgIvAjgCQQJLAlQCXQJnAnECegKEAo4CmAKiAqwCtgLBAssC1QLgAusC9QMAAwsDFgMhAy0DOANDA08DWgNmA3IDfgOKA5YDogOuA7oDxwPTA+AD7AP5BAYEEwQgBC0EOwRIBFUEYwRxBH4EjASaBKgEtgTEBNME4QTwBP4FDQUcBSsFOgVJBVgFZwV3BYYFlgWmBbUFxQXVBeUF9gYGBhYGJwY3BkgGWQZqBnsGjAadBq8GwAbRBuMG9QcHBxkHKwc9B08HYQd0B4YHmQesB78H0gflB/gICwgfCDIIRghaCG4IggiWCKoIvgjSCOcI+wkQCSUJOglPCWQJeQmPCaQJugnPCeUJ+woRCicKPQpUCmoKgQqYCq4KxQrcCvMLCwsiCzkLUQtpC4ALmAuwC8gL4Qv5DBIMKgxDDFwMdQyODKcMwAzZDPMNDQ0mDUANWg10DY4NqQ3DDd4N+A4TDi4OSQ5kDn8Omw62DtIO7g8JDyUPQQ9eD3oPlg+zD88P7BAJECYQQxBhEH4QmxC5ENcQ9RETETERTxFtEYwRqhHJEegSBxImEkUSZBKEEqMSwxLjEwMTIxNDE2MTgxOkE8UT5RQGFCcUSRRqFIsUrRTOFPAVEhU0FVYVeBWbFb0V4BYDFiYWSRZsFo8WshbWFvoXHRdBF2UXiReuF9IX9xgbGEAYZRiKGK8Y1Rj6GSAZRRlrGZEZtxndGgQaKhpRGncanhrFGuwbFBs7G2MbihuyG9ocAhwqHFIcexyjHMwc9R0eHUcdcB2ZHcMd7B4WHkAeah6UHr4e6R8THz4faR+UH78f6iAVIEEgbCCYIMQg8CEcIUghdSGhIc4h+yInIlUigiKvIt0jCiM4I2YjlCPCI/AkHyRNJHwkqyTaJQklOCVoJZclxyX3JicmVyaHJrcm6CcYJ0kneierJ9woDSg/KHEooijUKQYpOClrKZ0p0CoCKjUqaCqbKs8rAis2K2krnSvRLAUsOSxuLKIs1y0MLUEtdi2rLeEuFi5MLoIuty7uLyQvWi+RL8cv/jA1MGwwpDDbMRIxSjGCMbox8jIqMmMymzLUMw0zRjN/M7gz8TQrNGU0njTYNRM1TTWHNcI1/TY3NnI2rjbpNyQ3YDecN9c4FDhQOIw4yDkFOUI5fzm8Ofk6Njp0OrI67zstO2s7qjvoPCc8ZTykPOM9Ij1hPaE94D4gPmA+oD7gPyE/YT+iP+JAI0BkQKZA50EpQWpBrEHuQjBCckK1QvdDOkN9Q8BEA0RHRIpEzkUSRVVFmkXeRiJGZ0arRvBHNUd7R8BIBUhLSJFI10kdSWNJqUnwSjdKfUrESwxLU0uaS+JMKkxyTLpNAk1KTZNN3E4lTm5Ot08AT0lPk0/dUCdQcVC7UQZRUFGbUeZSMVJ8UsdTE1NfU6pT9lRCVI9U21UoVXVVwlYPVlxWqVb3V0RXklfgWC9YfVjLWRpZaVm4WgdaVlqmWvVbRVuVW+VcNVyGXNZdJ114XcleGl5sXr1fD19hX7NgBWBXYKpg/GFPYaJh9WJJYpxi8GNDY5dj62RAZJRk6WU9ZZJl52Y9ZpJm6Gc9Z5Nn6Wg/aJZo7GlDaZpp8WpIap9q92tPa6dr/2xXbK9tCG1gbbluEm5rbsRvHm94b9FwK3CGcOBxOnGVcfByS3KmcwFzXXO4dBR0cHTMdSh1hXXhdj52m3b4d1Z3s3gReG54zHkqeYl553pGeqV7BHtje8J8IXyBfOF9QX2hfgF+Yn7CfyN/hH/lgEeAqIEKgWuBzYIwgpKC9INXg7qEHYSAhOOFR4Wrhg6GcobXhzuHn4gEiGmIzokziZmJ/opkisqLMIuWi/yMY4zKjTGNmI3/jmaOzo82j56QBpBukNaRP5GokhGSepLjk02TtpQglIqU9JVflcmWNJaflwqXdZfgmEyYuJkkmZCZ/JpomtWbQpuvnByciZz3nWSd0p5Anq6fHZ+Ln/qgaaDYoUehtqImopajBqN2o+akVqTHpTilqaYapoum/adup+CoUqjEqTepqaocqo+rAqt1q+msXKzQrUStuK4trqGvFq+LsACwdbDqsWCx1rJLssKzOLOutCW0nLUTtYq2AbZ5tvC3aLfguFm40blKucK6O7q1uy67p7whvJu9Fb2Pvgq+hL7/v3q/9cBwwOzBZ8Hjwl/C28NYw9TEUcTOxUvFyMZGxsPHQce/yD3IvMk6ybnKOMq3yzbLtsw1zLXNNc21zjbOts83z7jQOdC60TzRvtI/0sHTRNPG1EnUy9VO1dHWVdbY11zX4Nhk2OjZbNnx2nba+9uA3AXcit0Q3ZbeHN6i3ynfr+A24L3hROHM4lPi2+Nj4+vkc+T85YTmDeaW5x/nqegy6LzpRunQ6lvq5etw6/vshu0R7ZzuKO6070DvzPBY8OXxcvH/8ozzGfOn9DT0wvVQ9d72bfb794r4Gfio+Tj5x/pX+uf7d/wH/Jj9Kf26/kv+3P9t////2wCEAAMEBAQGBAYHBwYICQgJCAwLCgoLDBINDg0ODRIcERQRERQRHBgdGBYYHRgsIh4eIiwyKigqMj02Nj1MSUxkZIYBAwQEBAYEBgcHBggJCAkIDAsKCgsMEg0ODQ4NEhwRFBERFBEcGB0YFhgdGCwiHh4iLDIqKCoyPTY2PUxJTGRkhv/CABEIAIIAggMBIgACEQEDEQH/xAA1AAACAQUBAQAAAAAAAAAAAAAAAQIDBAUGBwgJAQACAwEBAAAAAAAAAAAAAAACBAEDBQAG/9oADAMBAAIQAxAAAAD5aTjJ2lMdgob7kpEdFTjHKMkMwAAtj+kvzR9wa210o4WNbfjKUXheImmjge+fRLWY+WMfdfhdYIAkaiLBmKlESl2rjHQCbZ0ocb85NNPIlKmyHuPavE/Y2dfOcA9DefV6qBUcZ9KLUQkAFne4ectpN/rJzkB7RJRZYTaCFuL7qtEImrTnCeSaiEnsfWV5+oOc+iY4+Y489GJaYLDRIsCeAr90V647N6JrwBP6WaA1b86/R/nnpeLRuOL0q6oeyJbHV8wE0UGJzBlMXfF3U+q8muN7V7buPlHJLOeluXYPRsZnlWTxAXl7ronNAy2o00WsqjLlwZMK4oPu2q0wMQvrKkFTsFjkMtaxosusc5vosIVreuuJIWsmMME3M4plZnNAuZ2RZyvq9w3+xa5kU9TeNAhiXqcZXyN49m4UypdOuyDzV1/INSmnSC/lIKidwDYWdcMBynIL68rEPWZ9qAox/8QANxAAAQMCBAUCBQIDCQAAAAAAAQIDEQAEBQYSIRMgMUFREHEHIjKBsSVhMEKhFjM0YpGSosHR/9oACAEBAAE/AKjnjlgVl3ChiWN2NnrKQ++hsqAmATuas8s4Jh1mhlgC3aQojrBjysiSo/vSrawKidbe57gE/f0HofSeY+uDYo7h2KWt22JWw6lwDzpPT71c55axO1adKHmVKaCg2pMBCjERTr+HqdWo3LpJUSTwh/76Dk0n296IMA1vzpMGavviAxdttFVgG3Q2NZbXCFLA6xEgGjmiT/cf8z6ifTJeVbrH8cZsmlJQDK3XFHZDaeqv+gPNYF8OcqYc2lDdmwCdit1HFVqj+Zaq+LGXMhpwC4u0i3tL5EBkNI0F1fdCgPqpUajHTnDTpAIQog94rLOUnsSLq3XC003pkhMqJVvAo/DGxn/Euj9i416TU0K+GudrHL7uJKfbJL9shKFBOrdCiY+80x8TLzGmn1N6myCnX5jpq2rM+WMZxfFG3LZsuuLQEqkxp0+SeiaWkpURIMHqPQCTW4PJg9whF6yl0yyVp1iewMmKTidi5xHbUhsFRKUfSABtBFDG3gB9X+0cu1ZRvcv2Fsp966Up1SIW1piN5jyaxX4nXTuHv2tszwGnNbSlp2KdXcRT7eh0pKkmO6dxFJTNKX2T05sLxNlhRK0kqUI1+BS8SBUSH0wTtyzSVEGaW6pRVEgKiRPpJCffmsss4rctJcSgIQpOpJWYkeQBJrE8t4nYN8R1CS3tKkGQJ80gJ0JhKogd+Y+p6cuXrFq8xqzYc+hbo1DyBuRTrbaIB0hS+01m28/Tnmi4SXJ9hBpNw2EiWUn+CqggnpB9t6sMvYzetcRi1WpvprMJR9iqKxLLeM2LPFftiG5jWkhaZ/cj0wCwsbG0aKAOLw9anIgmR5/Aq/x68U4tIQNckHzJPj7UMv3uIhTjzyp2nSR39/60rKuHpUQbpcgwYgj8c4kmmmXFupQlJK1KCQkdZJgCspZOsrABb7bS7jTK3FBKgggxCQaOV8vYqhC3rS3uAggIUW0pII3JkRI/amba3YY0pKISJQlI7CO1Zjt8OClJPA4DgKXUqMAg7/1708GhcLCVHQFkA99M0L+5sENJS5xGtAKF9yBT2N6boPFMqg/6nvTeZsWdSqFpCQZGkUl/FykEa4IkfKebDLE3d+ywFhOtUSewAk1YsM2r6kIbAA2JB3+5qxs8NXcW906yhwtKC2yrrr7SfFKxlUrQQdIMH38kVg2MfpbhlMcaIPgAAzTuPPtpniEqIlW0bp2HvWY8VFzgGIJKzxA0VAzEFNTpVtTeJ3KGuGFSgmSlQmnHlLXJgUxmW1ZQ1DCVL6LWnYgDsDTmaMX1q0PQmTAIBMc1jdPW94y839aFgilX7S3QpTRQ4NI0/mrzMiLS00MIUXATBJ2APmra+Wu2bL1+gkzJ3NWeakWLhQh0vIUpMJ6b+adxsOpCnFECTsBuZrHL5T1k6lMBJT07n35DRUqea3dDb7aykK0rCoO0xT9wyt/U05sfmAVsRPb7VdXTPBKQrUojqO1IWkESJFFfyxHeQaYxa60aFKSRESesVd3i3YE9PHoBUUqt+eeTDcHXcp1rJSjfT/m09a/s0px7S05A1QVL6CnMjtBkab35yNtSIRP5FXNo9bvradTpWgwRStvTT/Bg0EKq1vrlNuhr+VM/matcQcDQExuVU1iSuEJJJH3n3rG7sXN0FQPlRp2pclVIt+5rg+sUEK8Vw1Vwx5rSmhA7UFJ8UnTINB8D6QO9G6bLQ+Udt4py7WWyAqB33oqE00hMzFaUitvRPakAeiuvr4oV2PtRJk1bEykT5p4mOvmm/ppHSj9JqTX/xAAzEQACAQMCBAEICwAAAAAAAAABAgADBBESIRATMWEgBTJBUYGRkqEUFRYiM0NSU2Jxgv/aAAgBAgEBPwAQeA8LG9p2yux2bbDY6CfaCv8Aw+JYIJa2D1lLalVBtqMu7bkvjWrZHVfAtA1SExnJ/qfUL+pfjg4G8qrR07kDOB3MFRnGWG/gWoyg4nOrd/nBB4DFUswA6k4EqWVpTotlm1Ade85fY+FPI9TlgtVRXIzoOYvkqyNM5uG1gez3S0rpQquxAJGwPXE51MuS5dhnYZnPp/tcV06hnpneLfUUPoI/TjYRvKjGoTg43+cF9UFb7pJBGCT34LspmV7+DSNWeCWlQjUE69IbSsuCy7e+VQFAE0mCaYKTn0GC3cwWnrMqVCM+cDgASyZmDAn2SnYgsXc57T6LS7QRY0XzpW/D/wAy56mWPnT8ocP/xAAqEQABBAECBAQHAAAAAAAAAAABAAIDERAEEhMhMUEgUVJhBRQiMkJy8P/aAAgBAwEBPwDwjHw+KF4ddFw7L5XTenMUEknQKSJ8bqcPBBNPHezv7WuPr/4Z0Ur9wZuAbRs9FrWwh9scTfVVnTzBv0mqPdcVvmEcklHABJARgO0m0JR7I5ooaeRwsBP0czRahAJsovYbBK4cPkcUgOaDI9oJ6BRyMAFkBahzTC4e3IIEg8imzPaTS403rKtWgeaMxIKtGSRzasp4c0C01WM8lYW5Q/sFqpLACMnYLcjgY/IKJT9Uz7zj/9k="
            />
          )}
        </EuiFlexItem>
      </EuiFlexGroup>
    </>
  );
};
