agents:
  provider: gcp

steps:
  - label: ':npm: Update package version'
    key: 'update-package-version'
    command: '.buildkite/scripts/release/step_update_version.sh'
    agents:
      provider: k8s
      ephemeralStorage: '10G'
      cpu: '1000m'
      memory: '1G'
    if: build.branch != "main"
#  - label: ':docker: Build agent image'
#    key: 'build-agent-image'
#    command: '.buildkite/scripts/drivah.sh .'
#    agents:
#      provider: k8s
#      image: 'docker.elastic.co/ci-agent-images/drivah:0.24.4'
#      ephemeralStorage: '20G'
#      cpu: '2000m'
#      # running yarn install requires plenty of memory
#      memory: '8G'
#  - wait
#  - label: 'Check image contents'
#    command: 'ls -la; yarn list'
#    agents:
#      provider: k8s
#      image: 'docker.elastic.co/eui/ci-images/eui:${BUILDKITE_COMMIT}'
