# 🏠/.buildkite/pipelines/pipeline_pull_request_test.yml

steps:
  - agents:
      provider: "gcp"
    command: .buildkite/scripts/pipeline_test.sh
    if: build.branch != "main"
    artifact_paths:
      - "cypress/screenshots/**/*.png"
