agents:
  provider: gcp

steps:
  - group: ':hammer: Run tests'
    key: 'tests'
    steps:
      - label: ':cypress: Cypress tests on React 18'
        command: '.buildkite/scripts/pipelines/pipeline_test.sh'
        env:
          TEST_TYPE: 'cypress:18'
        artifact_paths:
          - 'cypress/screenshots/**/*.png'
          - 'cypress/videos/**/*.mp4'
        agents:
          provider: gcp
          machineType: 'n2-standard-2'
          preemptible: true
  - wait
  - label: ':npm: Update package version'
    key: 'update-package-version'
    command: '.buildkite/scripts/release/step_update_version.sh'
    agents:
      provider: k8s
      ephemeralStorage: '10G'
      cpu: '1000m'
      memory: '1G'
    if: build.branch != "main"
#  - label: ':docker: Build agent image'
#    key: 'build-agent-image'
#    command: '.buildkite/scripts/drivah.sh .'
#    agents:
#      provider: k8s
#      image: 'docker.elastic.co/ci-agent-images/drivah:0.24.4'
#      ephemeralStorage: '20G'
#      cpu: '2000m'
#      # running yarn install requires plenty of memory
#      memory: '8G'
#  - wait
#  - label: 'Check image contents'
#    command: 'ls -la; yarn list'
#    agents:
#      provider: k8s
#      image: 'docker.elastic.co/eui/ci-images/eui:${BUILDKITE_COMMIT}'
