## 🏠/.buildkite/pipelines/pipeline_pull_request_test_and_deploy.yml

steps:
  - group: ":hammer_and_pick: Run tests and deploy docs on pull request"
    key: "pull-request-test"
    steps:
      - command: ".buildkite/pipelines/pipeline_pull_request_test.yml"
      - wait
      - command: ".buildkite/pipelines/pipeline_pull_request_deploy.yml"

