# 🏠/.buildkite/pipelines/pipeline_pull_request_test.yml

steps:
  - command: .buildkite/scripts/pipeline_test.sh
    label: ":typescript: Linting"
    agents:
      provider: "gcp"
    env:
      TEST_TYPE: 'lint'
    if: build.branch != "main" # We're skipping testing commits in main for now to maintain parity with previous Jenkins setup
  - command: .buildkite/scripts/pipeline_test.sh
    label: ":jest: Unit tests"
    agents:
      provider: "gcp"
    env:
      TEST_TYPE: 'unit'
    if: build.branch != "main" # We're skipping testing commits in main for now to maintain parity with previous Jenkins setup
  - command: .buildkite/scripts/pipeline_test.sh
    label: ":cypress: Cypress tests on React 16"
    agents:
      provider: "gcp"
    env:
      TEST_TYPE: 'cypress:16'
    if: build.branch != "main" # We're skipping testing commits in main for now to maintain parity with previous Jenkins setup
    artifact_paths:
      - "cypress/react16/screenshots/**/*.png"
  - command: .buildkite/scripts/pipeline_test.sh
    label: ":cypress: Cypress tests on React 17"
    agents:
      provider: "gcp"
    env:
      TEST_TYPE: 'cypress:17'
    if: build.branch != "main" # We're skipping testing commits in main for now to maintain parity with previous Jenkins setup
    artifact_paths:
      - "cypress/react17/screenshots/**/*.png"
  - command: .buildkite/scripts/pipeline_test.sh
    label: ":cypress: Cypress tests on React 18"
    agents:
      provider: "gcp"
    env:
      TEST_TYPE: 'cypress:18'
    if: build.branch != "main" # We're skipping testing commits in main for now to maintain parity with previous Jenkins setup
    artifact_paths:
      - "cypress/react18/screenshots/**/*.png"
