# 🏠/.buildkite/pipelines/pipeline_pull_request_test.yml

steps:
  - label: ":docker: Cached container"
    key: "build-test-container"
    command: .buildkite/scripts/pipelines/pipeline_docker_build.sh
    agents:
      provider: "gcp"
    if: build.branch != "main" # This job is triggered by the combined test and deploy docs for every PR

  - label: ":typescript: Linting"
    command: .buildkite/scripts/pipelines/pipeline_test.sh
    depends_on: "build-test-container" # The depends_on creates an implicit "wait" while the container builds
    agents:
      provider: "gcp"
    env:
      TEST_TYPE: 'lint'
    if: build.branch != "main"
  
  - label: ":jest: TS unit tests"
    command: .buildkite/scripts/pipelines/pipeline_test.sh
    depends_on: "build-test-container"
    agents:
      provider: "gcp"
    env:
      TEST_TYPE: 'unit:ts'
    if: build.branch != "main"
  
  - label: ":jest: TSX unit tests on React 16"
    command: .buildkite/scripts/pipelines/pipeline_test.sh
    depends_on: "build-test-container"
    agents:
      provider: "gcp"
    env:
      TEST_TYPE: 'unit:tsx:16'
    if: build.branch != "main"
  
  - label: ":jest: TSX unit tests on React 17"
    command: .buildkite/scripts/pipelines/pipeline_test.sh
    depends_on: "build-test-container"
    agents:
      provider: "gcp"
    env:
      TEST_TYPE: 'unit:tsx:17'
    if: build.branch != "main"
  
  - label: ":jest: TSX unit tests on React 18"
    command: .buildkite/scripts/pipelines/pipeline_test.sh
    depends_on: "build-test-container"
    agents:
      provider: "gcp"
    env:
      TEST_TYPE: 'unit:tsx'
    if: build.branch != "main"
  
  - label: ":cypress: Cypress tests on React 16"
    command: .buildkite/scripts/pipelines/pipeline_test.sh
    depends_on: "build-test-container"
    agents:
      provider: "gcp"
    env:
      TEST_TYPE: 'cypress:16'
    if: build.branch != "main"
    artifact_paths:
      - "cypress/screenshots/**/*.png"
      - "cypress/videos/**/*.mp4"
  
  - label: ":cypress: Cypress tests on React 17"
    command: .buildkite/scripts/pipelines/pipeline_test.sh
    depends_on: "build-test-container"
    agents:
      provider: "gcp"
    env:
      TEST_TYPE: 'cypress:17'
    if: build.branch != "main"
    artifact_paths:
      - "cypress/screenshots/**/*.png"
      - "cypress/videos/**/*.mp4"
  
  - label: ":cypress: Cypress tests on React 18"
    command: .buildkite/scripts/pipelines/pipeline_test.sh
    depends_on: "build-test-container"
    agents:
      provider: "gcp"
    env:
      TEST_TYPE: 'cypress:18'
    if: build.branch != "main"
    artifact_paths:
      - "cypress/screenshots/**/*.png"
      - "cypress/videos/**/*.mp4"

  - label: ":axe: Cypress accessibility (a11y) tests on React 18"
    command: .buildkite/scripts/pipelines/pipeline_test.sh
    depends_on: "build-test-container"
    agents:
      provider: "gcp"
    env:
      TEST_TYPE: 'cypress:a11y'
    if: build.branch != "main"
    artifact_paths:
      - "cypress/screenshots/**/*.png"
      - "cypress/videos/**/*.mp4"
