# 🏠/.buildkite/pipelines/pipeline_pull_request_test.yml

steps:
  - label: ":docker: Build containers"
    # TODO: See Jessica David's work for way to build your own Docker image and upload it via shell script, securely.
    # In your shell script:
    # Get vault password to log into Docker Hub
    # Assume we're building in Buildkite and exit 1 if not (maybe)
    # Build the optimzed image using `docker-compose`
    # Push the image to Docker Hub
    #
    # OR...
    #
    # Just change the agents > provider to agents > image and use our specific, already built and optimized image from Docker Hub
    # docker.elastic.co/eui/composed:1.0 for instance
    # Now Biff, remember that it'll either be a LOT of duplicated find and replace, OR introduce an environment variable with the Docker image.

  - label: ":typescript: Linting"
    command: .buildkite/scripts/pipeline_test.sh
    agents:
      provider: "gcp"
    env:
      TEST_TYPE: 'lint'
    if: build.branch != "main" # This job is triggered by the combined test and deploy docs for every PR
  
  - label: ":jest: TS unit tests"
    command: .buildkite/scripts/pipeline_test.sh
    agents:
      provider: "gcp"
    env:
      TEST_TYPE: 'unit:ts'
    if: build.branch != "main"
  
  - label: ":jest: TSX unit tests on React 16"
    command: .buildkite/scripts/pipeline_test.sh
    agents:
      provider: "gcp"
    env:
      TEST_TYPE: 'unit:tsx:16'
    if: build.branch != "main"
  
  - label: ":jest: TSX unit tests on React 17"
    command: .buildkite/scripts/pipeline_test.sh
    agents:
      provider: "gcp"
    env:
      TEST_TYPE: 'unit:tsx:17'
    if: build.branch != "main"
  
  - label: ":jest: TSX unit tests on React 18"
    command: .buildkite/scripts/pipeline_test.sh
    agents:
      provider: "gcp"
    env:
      TEST_TYPE: 'unit:tsx'
    if: build.branch != "main"
  
  - label: ":cypress: Cypress tests on React 16"
    command: .buildkite/scripts/pipeline_test.sh
    agents:
      provider: "gcp"
    env:
      TEST_TYPE: 'cypress:16'
    if: build.branch != "main"
    artifact_paths:
      - "cypress/screenshots/**/*.png"
      - "cypress/videos/**/*.mp4"
  
  - label: ":cypress: Cypress tests on React 17"
    command: .buildkite/scripts/pipeline_test.sh
    agents:
      provider: "gcp"
    env:
      TEST_TYPE: 'cypress:17'
    if: build.branch != "main"
    artifact_paths:
      - "cypress/screenshots/**/*.png"
      - "cypress/videos/**/*.mp4"
  
  - label: ":cypress: Cypress tests on React 18"
    command: .buildkite/scripts/pipeline_test.sh
    agents:
      provider: "gcp"
    env:
      TEST_TYPE: 'cypress:18'
    if: build.branch != "main"
    artifact_paths:
      - "cypress/screenshots/**/*.png"
      - "cypress/videos/**/*.mp4"
