agents:
  provider: gcp

steps:
  - label: ':docker: Build agent image'
    key: 'build-agent-image'
    command: '.buildkite/scripts/drivah.sh .'
    agents:
      provider: k8s
      image: 'docker.elastic.co/ci-agent-images/drivah:0.24.4'
      ephemeralStorage: '10G'
      cpu: '2000m'
      memory: '3G'
  - wait
  - command: "echo 'TODO: push agent image'"
