## 🏠/.buildkite/pipelines/pipeline_pull_request_test.yml

steps:
  - label: ":hammer: EUI pull request test"
    agents:
      provider: "gcp"
    command: .buildkite/scripts/pipeline_pull_request_test.sh
