# 🏠/.buildkite/pipelines/pipeline_pull_request_test.yml

agents:
  provider: gcp
  machineType: c4d-standard-4
  preemptible: true
  diskType: hyperdisk-balanced
  diskSizeGb: 30
  # c4d instances are only available in some regions
  spotZones: us-central1-a,us-central1-b,us-central1-c

retry_policy: &retry_policy
  automatic:
    - exit_status: -1 # agent loss
      limit: 3
    - exit_status: "*"
      limit: 2

steps:
  - command: .buildkite/scripts/pipelines/pipeline_test.sh
    label: ":typescript: Linting"
    env:
      TEST_TYPE: 'lint'
    if: build.branch != "main" # This job is triggered by the combined test and deploy docs for every PR
    retry: *retry_policy

  - command: .buildkite/scripts/pipelines/pipeline_test.sh
    label: ":jest: TS unit tests"
    env:
      TEST_TYPE: 'unit:ts'
    if: build.branch != "main"
    retry: *retry_policy

  - command: .buildkite/scripts/pipelines/pipeline_test.sh
    label: ":jest: TSX unit tests on React 17"
    env:
      TEST_TYPE: 'unit:tsx:17'
    if: build.branch != "main"
    retry: *retry_policy

  - command: .buildkite/scripts/pipelines/pipeline_test.sh
    label: ":jest: TSX unit tests on React 18"
    env:
      TEST_TYPE: 'unit:tsx'
    if: build.branch != "main"
    retry: *retry_policy

  - command: .buildkite/scripts/pipelines/pipeline_test.sh
    label: ":cypress: Cypress tests on React 17"
    env:
      TEST_TYPE: 'cypress:17'
    if: build.branch != "main"
    artifact_paths:
      - "cypress/screenshots/**/*.png"
      - "cypress/videos/**/*.mp4"
    timeout_in_minutes: 45
    retry: *retry_policy

  - command: .buildkite/scripts/pipelines/pipeline_test.sh
    label: ":cypress: Cypress tests on React 18"
    env:
      TEST_TYPE: 'cypress:18'
    if: build.branch != "main"
    artifact_paths:
      - "cypress/screenshots/**/*.png"
      - "cypress/videos/**/*.mp4"
    timeout_in_minutes: 45
    retry: *retry_policy

  - command: .buildkite/scripts/pipelines/pipeline_test.sh
    label: ":axe: Cypress accessibility (a11y) tests on React 18"
    env:
      TEST_TYPE: 'cypress:a11y'
    if: build.branch != "main"
    artifact_paths:
      - "cypress/screenshots/**/*.png"
      - "cypress/videos/**/*.mp4"
    timeout_in_minutes: 45
    retry: *retry_policy
