## 🏠/.buildkite/pipelines/pipeline_pull_request_deploy_docs.yml

steps:
  - command: .buildkite/scripts/pipelines/pipeline_deploy_docs.sh
    label: ":newspaper: Build and deploy EUI documentation website"
    agents:
      provider: "gcp"
    if: build.branch != "main" # We don't want to deploy docs on main, only on manual release
  - command: .buildkite/scripts/pipelines/pipeline_deploy_new_docs.sh
    label: ":docusaurus: Build and deploy new documentation website"
    agents:
      provider: gcp
      machineType: "n2-standard-2"
      image: "family/eui-ubuntu-2204"
    if: build.branch != "main"
