agents:
  provider: gcp
  machineType: 'n2-standard-2'
  preemptible: true

steps:
  - group: ':hammer: Unit and static tests'
    key: 'unit-static-tests'
    steps:
      - label: ':typescript: Linting'
        command: '.buildkite/scripts/pipelines/pipeline_test.sh'
        env:
          TEST_TYPE: 'lint'
        agents:
          machineType: 'n1-standard-1'
        timeout_in_minutes: 15
        retry:
          automatic:
            - exit_status: '-1'
              limit: 1
      - label: ':jest: TS unit tests'
        command: '.buildkite/scripts/pipelines/pipeline_test.sh'
        env:
          TEST_TYPE: 'unit:ts'
        agents:
          machineType: 'n1-standard-1'
        timeout_in_minutes: 60
        retry:
          automatic:
            - exit_status: '-1'
              limit: 1
      - label: ':jest: TSX unit tests on React 17'
        command: '.buildkite/scripts/pipelines/pipeline_test.sh'
        env:
          TEST_TYPE: 'unit:tsx:17'
        timeout_in_minutes: 60
        retry:
          automatic:
            - exit_status: '-1'
              limit: 1
      - label: ':jest: TSX unit tests on React 18'
        command: '.buildkite/scripts/pipelines/pipeline_test.sh'
        env:
          TEST_TYPE: 'unit:tsx'
        timeout_in_minutes: 60
        retry:
          automatic:
            - exit_status: '-1'
              limit: 1
  - group: ':hammer: E2E component tests'
    key: 'e2e-tests'
    steps:
      - label: ':cypress: Cypress tests on React 17'
        command: '.buildkite/scripts/pipelines/pipeline_test.sh'
        env:
          TEST_TYPE: 'cypress:17'
        artifact_paths:
          - 'cypress/screenshots/**/*.png'
          - 'cypress/videos/**/*.mp4'
        timeout_in_minutes: 60
        retry:
          automatic:
            - exit_status: '-1'
              limit: 1
      - label: ':cypress: Cypress tests on React 18'
        command: '.buildkite/scripts/pipelines/pipeline_test.sh'
        env:
          TEST_TYPE: 'cypress:18'
        artifact_paths:
          - 'cypress/screenshots/**/*.png'
          - 'cypress/videos/**/*.mp4'
        timeout_in_minutes: 60
        retry:
          automatic:
            - exit_status: '-1'
              limit: 1
  - wait
  - label: ':npm: Update version, build and publish package'
    key: 'update-build-and-publish'
    commands:
      - .buildkite/scripts/release/step_update_version.sh
      - .buildkite/scripts/release/step_build.sh
      - .buildkite/scripts/release/step_commit_and_publish.sh
    agents:
      image: 'docker.elastic.co/ci-agent-images/eui/basic-buildkite-agent:latest'
      provider: k8s
      ephemeralStorage: '20G'
      cpu: '4000m'
      memory: '8G'
    if: build.branch != "main"
