# 🏠/.buildkite/pipelines/pipeline_pull_request_test.yml

steps:
  - label: ":docker: Build containers"
    agents:
      provider: "gcp"
    plugins:
      - docker-compose#v4.15.0:
          build:
            - deps
            - app
          image-name:
            - docker.elastic.co/eui/buildkite/deps:1.0
            - docker.elastic.co/eui/buildkite/app:1.0
          image-repository: docker.elastic.co/eui/buildkite

  - wait

  - label: ":typescript: Linting"
    command: .buildkite/scripts/pipeline_test.sh
    agents:
      provider: "gcp"
    plugins:
      - docker-compose#4.15.0:
          run: app
    env:
      TEST_TYPE: 'lint'
    if: build.branch != "main" # This job is triggered by the combined test and deploy docs for every PR
  
  # - label: ":jest: TS unit tests"
  #   command: .buildkite/scripts/pipeline_test.sh
  #   agents:
  #     provider: "gcp"
  #   plugins:
  #     - docker-compose#4.15.0:
  #         run: app
  #   env:
  #     TEST_TYPE: 'unit:ts'
  #   if: build.branch != "main"
  
  # - label: ":jest: TSX unit tests on React 16"
  #   command: .buildkite/scripts/pipeline_test.sh
  #   agents:
  #     provider: "gcp"
  #   plugins:
  #     - docker-compose#4.15.0:
  #         run: app
  #   env:
  #     TEST_TYPE: 'unit:tsx:16'
  #   if: build.branch != "main"
  
  # - label: ":jest: TSX unit tests on React 17"
  #   command: .buildkite/scripts/pipeline_test.sh
  #   agents:
  #     provider: "gcp"
  #   plugins:
  #     - docker-compose#4.15.0:
  #         run: app
  #   env:
  #     TEST_TYPE: 'unit:tsx:17'
  #   if: build.branch != "main"
  
  # - label: ":jest: TSX unit tests on React 18"
  #   command: .buildkite/scripts/pipeline_test.sh
  #   agents:
  #     provider: "gcp"
  #   plugins:
  #     - docker-compose#4.15.0:
  #         run: app
  #   env:
  #     TEST_TYPE: 'unit:tsx'
  #   if: build.branch != "main"
  
  # - label: ":cypress: Cypress tests on React 16"
  #   command: .buildkite/scripts/pipeline_test.sh
  #   agents:
  #     provider: "gcp"
  #   plugins:
  #     - docker-compose#4.15.0:
  #         run: app
  #   env:
  #     TEST_TYPE: 'cypress:16'
  #   if: build.branch != "main"
  #   artifact_paths:
  #     - "cypress/screenshots/**/*.png"
  #     - "cypress/videos/**/*.mp4"
  
  # - label: ":cypress: Cypress tests on React 17"
  #   command: .buildkite/scripts/pipeline_test.sh
  #   agents:
  #     provider: "gcp"
  #   plugins:
  #   - docker-compose#4.15.0:
  #       run: app
  #   env:
  #     TEST_TYPE: 'cypress:17'
  #   if: build.branch != "main"
  #   artifact_paths:
  #     - "cypress/screenshots/**/*.png"
  #     - "cypress/videos/**/*.mp4"
  
  # - label: ":cypress: Cypress tests on React 18"
  #   command: .buildkite/scripts/pipeline_test.sh
  #   agents:
  #     provider: "gcp"
  #   plugins:
  #     - docker-compose#4.15.0:
  #         run: app
  #   env:
  #     TEST_TYPE: 'cypress:18'
  #   if: build.branch != "main"
  #   artifact_paths:
  #     - "cypress/screenshots/**/*.png"
  #     - "cypress/videos/**/*.mp4"
