## 🏠/.buildkite/pipelines/pipeline_release_deploy_docs.yml

steps:
  - agents:
      provider: "gcp"
    command: .buildkite/scripts/pipeline_deploy_docs.sh
  - build:
      env:
        GIT_BRANCH: "${BUILDKITE_BRANCH}"
        GIT_PULL_REQUEST_ID: "${BUILDKITE_PULL_REQUEST}"
        BUILDKITE_CI: "${BUILDKITE}"
