## 🏠/.buildkite/pipelines/pipeline_pull_request_test_and_deploy.yml

steps:
  - trigger: "eui-pull-request-test"
    label: ":hammer: EUI pull request test"
    build:
      branch: "${BUILDKITE_BRANCH}"
  - trigger: "eui-pull-request-deploy-docs"
    label: ":newspaper: EUI pull request deploy docs"
    build:
      branch: "${BUILDKITE_BRANCH}"
      env:
        GIT_BRANCH: "${BUILDKITE_BRANCH}"
        GIT_PULL_REQUEST_ID: "${BUILDKITE_PULL_REQUEST}"
        BUILDKITE_CI: "${BUILDKITE}"
        BUILDKITE_PULL_REQUEST: "${BUILDKITE_PULL_REQUEST}"
        BUILDKITE_PULL_REQUEST_BASE_BRANCH: "${BUILDKITE_PULL_REQUEST_BASE_BRANCH}"
