## 🏠/.buildkite/pipelines/pipeline_pull_request_test_and_deploy.yml

steps:
  - trigger: "eui-pull-request-test"
    key: "test"
    label: ":hammer: EUI pull request test"
    build:
      branch: "${BUILDKITE_BRANCH}"
      commit: "${BUILDKITE_COMMIT}"
  - trigger: "eui-pull-request-deploy-docs"
    key: "deploy-docs"
    label: ":newspaper: EUI pull request deploy docs"
    build:
      branch: "${BUILDKITE_BRANCH}"
      commit: "${BUILDKITE_COMMIT}"
      env:
        GIT_BRANCH: "${BUILDKITE_BRANCH}"
        GIT_PULL_REQUEST_ID: "${BUILDKITE_PULL_REQUEST}"
  - # depends_on: "deploy-docs"
    label: ":camera_with_flash: Visual regression tests"
    command: ".buildkite/scripts/visual_regression/run_loki.sh"
    artifact_paths:
      - "packages/eui/.loki/difference/*.png"
      - "packages/eui/.loki/current/*.png"
    agents:
      provider: "gcp"
      # Loki isn't resource heavy and doesn't benefit
      # from faster CPUs like the n2 family
      machineType: 'n1-standard-1'
      # Use spot instances
      # https://cloud.google.com/spot-vms
      preemptible: true
      image: "family/eui-ubuntu-2204"
    retry:
      automatic:
        - exit_status: '-1'
          limit: 1
