## 🏠/.buildkite/pipelines/pipeline_pull_request_test.yml

- agents:
    provider: "gcp"
- command: .buildkite/scripts/pipeline_pull_request_test.sh
- artifact_paths:
  - "cypress/screenshots/**/*.png"
