name: Update Kibana dependencies

on:
  workflow_dispatch:
    inputs:
      dependencies:
        description: JSON-serialized map of dependencies to update
        type: string
        required: true
      pr_title:
        description: PR title
        default: Update EUI dependencies
        type: string
      pr_body:
        description: PR body
        type: string
        default: ''
  workflow_call:
    inputs:
      dependencies:
        description: JSON-serialized map of dependencies to update
        type: string
        required: true
      pr_title:
        description: PR title
        default: Update EUI dependencies
        type: string
      pr_body:
        description: PR body
        type: string
        default: ''
    outputs:
      pr_url:
        description: 'URL of the created pull request'
        value: ${{ jobs.open_pr.outputs.pr_url }}

jobs:
  prepare_changes:
    name: Prepare changes
    uses: ./.github/workflows/update_kibana_dependencies__prepare_changes.yml
    with:
      dependencies: ${{ inputs.dependencies }}
  open_pr:
    name: Open PR
    needs: [prepare_changes]
    uses: ./.github/workflows/update_kibana_dependencies__open_pr.yml
    with:
      pr_head: eui-kibana:${{ needs.prepare_changes.outputs.branch_name }}
      pr_title: ${{ inputs.pr_title }}
      pr_body: ${{ inputs.pr_body }}
      pr_draft: true
      pr_labels: 'EUI,backport:skip,release_note:skip'
